if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c7fde9b41b5b',
	'title' => 'Light Armor	(new)',
	'fields' => array(
		array(
			'key' => 'field_5c7fe09b9b518',
			'label' => 'helm',
			'name' => 'helm',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47918 => 'Knight / Beigarth\'s',
				47937 => 'Celestial / Wupwup',
				47955 => 'Carrion / Occam\'s',
				47973 => 'Rabid / Ferratus\'s',
				47991 => 'Dire / Morbach\'s',
				48009 => 'Cleric / Tateos\'s',
				48027 => 'Magi / Hronk\'s',
				48045 => 'Apothecary / Veldrunner',
				48063 => 'Valkyrie / Gobrech\'s',
				48081 => 'Berserker / Zojja\'s',
				49620 => 'Zealot / Keeper\'s',
				48099 => 'Soldier / Ahamid\'s',
				85161 => 'Harrier /	Zehtuka\'s',
				48117 => 'Rampager / Forgemaster\'s',
				48153 => 'Settler / Leftpaw\'s',
				48189 => 'Shaman /	Zintl',
				48135 => 'Assasin / Saphir\'s',
				48171 => 'Cavalier / Angchu',
				66376 => 'Nomad / Ventari\'s',
				76834 => 'Trailblazer / Pahua\'s',
				73970 => 'Minstrel / Maklain\'s',
				88022 => 'Plaguedoctor / Nerashi\'s',
				75940 => 'Marauder / Svaard\'s',
				77108 => 'Crusader / Ossa\'s',
				73521 => 'Wanderer / Ruka\'s',
				74522 => 'Vigilant / Laranthir\'s',
				48207 => 'Sentinel / Wei Qi\'s',
				67442 => 'Sinister / Verata\'s',
				75727 => 'Commander / Tizlak\'s',
				85296 => 'Grieving / The Twins\'',
				75770 => 'Viper / Yassith\'s',
				85285 => 'Marshal / Nadijeh\'s',
				80661 => 'Seraph / Thackeray\'s',
				89912 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c81a01f9bc11',
			'label' => 'Shoulders',
			'name' => 'shoulders',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47916 => 'Knight / Beigarth\'s',
				47939 => 'Wupwup / Celestial',
				47957 => 'Carrion / Occam\'s',
				47975 => 'Rabid /	Ferratus\'s',
				47993 => 'Dire / Morbach\'s',
				48011 => 'Cleric / Tateos\'s',
				48029 => 'Magi / Hronk\'s',
				48047 => 'Apothecary / Veldrunner',
				48065 => 'Valkyrie / Gobrech\'s',
				48083 => 'Berserker / Zojja\'s',
				49618 => 'Zealot / Keeper\'s',
				48101 => 'Soldier / Ahamid\'s',
				85089 => 'Harrier / Zehtuka\'s',
				48119 => 'Rampager / Forgemaster\'s',
				48155 => 'Settler / Leftpaw\'s',
				48191 => 'Shaman / Zintl',
				48137 => 'Assassin / Saphir\'s',
				48173 => 'Cavalier / Angchu',
				66366 => 'Nomad / Ventari\'s',
				76834 => 'Trailblazer / Pahua\'s',
				73670 => 'Minstrel / Maklain\'s',
				88073 => 'Plaguedoctor / Nerashi\'s',
				76671 => 'Marauder / Svaard\'s',
				76186 => 'Crusader / Ossa\'s',
				71308 => 'Wanderer / Ruka\'s',
				75023 => 'Vigilant / Laranthir\'s',
				48209 => 'Sentinel / Wei Qi\'s',
				67449 => 'Sinister / Verata\'s',
				70555 => 'Commander / Tizlak\'s',
				85241 => 'Grieving / The Twins\'',
				73225 => 'Viper / Yassith\'s',
				85066 => 'Marshal / Nadijeh\'s',
				80448 => 'Serpah / Thackeray\'s',
				89628 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c826410dabf9',
			'label' => 'Coat',
			'name' => 'chest',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47920 => 'Knight / Beigarth\'s',
				47935 => 'Celestial / Wupwup',
				47953 => 'Carrion / Occam\'s',
				47971 => 'Rabid / Ferratus\'s',
				47989 => 'Dire / Morbach',
				48007 => 'Cleric / Tateos\'s',
				48025 => 'Magi / Hronk\'s',
				48043 => 'Apothecary / Veldrunner',
				48061 => 'Valkyrie / Gobrech\'s',
				48079 => 'Berserker /	Zojja\'s',
				49622 => 'Zealot / Keeper\'s',
				48097 => 'Soldier / Ahamid\'s',
				85098 => 'Harrier / Zehtuka\'s',
				48115 => 'Rampager / Forgemaster\'s',
				48151 => 'Settler /	Leftpaw\'s',
				48187 => 'Shaman / Zintl',
				48133 => 'Assassin / Saphir\'s',
				48169 => 'Cavelier / Angchu',
				66370 => 'Nomad / Ventari\'s',
				74524 => 'Trailblazer / Pahua\'s',
				74448 => 'Minstrel / Maklain\'s',
				87977 => 'Plaguedoctor/ Nerashi',
				71968 => 'Marauder / Svaard\'s',
				76854 => 'Crusader / Ossa\'s',
				72494 => 'Wanderer / Ruka\'s',
				73882 => 'Vigilant / Laranthir\'s',
				48205 => 'Sentinel / Wei Qi\'s',
				67453 => 'Sinister/ Verata\'s',
				72182 => 'Commander / Tizlak\'s',
				85319 => 'Grieving / The Twins\'',
				71436 => 'Viper / Yassith\'s',
				85288 => 'Marshal / Nadijeh\'s',
				80244 => 'Seraph / Thackeray\'s',
				89789 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c83ac0bfe722',
			'label' => 'gloves',
			'name' => 'gloves',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47919 => 'Knight / Beigarth\'s',
				47936 => 'Celestial / Wupwup',
				47954 => 'Carrion / Occam\'s',
				47972 => 'Rabid / Ferratus\'s',
				47990 => 'Dire / Morbach\'s',
				48008 => 'Cleric / Tateos\'s',
				48026 => 'Magi / Hronk\'s',
				48044 => 'Apothecary / Veldrunner',
				48062 => 'Valkyrie / Gobrech\'s',
				48080 => 'Berserker /	Zojja\'s',
				49621 => 'Zealot / Keeper\'s',
				48098 => 'Soldier / Ahamid\'s',
				85004 => 'Harrier / Zehtuka\'s',
				48116 => 'Rampager / Forgemaster\'s',
				48152 => 'Settler / Leftpaw\'s',
				48188 => 'Shaman / Zintl',
				48134 => 'Assassin / Saphir\'s',
				48170 => 'Cavalier / Angchu',
				66359 => 'Nomad /	Ventari\'s',
				70993 => 'Trailblazer / Pahua\'s',
				75866 => 'Minstrel / Maklain\'s',
				87960 => 'Plaguedoctor / Nerashi\'s',
				74518 => 'Marauder / Svaard\'s',
				74836 => 'Crusader / Ossa\'s',
				70699 => 'Wanderer / Ruka\'s',
				73882 => 'Vigilant / Laranthir\'s',
				48206 => 'Sentinel / Wei Qi\'s',
				67452 => 'Sinister / Verata\'s',
				77208 => 'Commander / Tizlak\'s',
				85048 => 'Grieving / The Twins\'',
				73852 => 'Viper / Yassith\'s',
				84866 => 'Marshal / Nadijeh\'s',
				80268 => 'Seraph / Thackeray\'s',
				89925 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c83d30ff3280',
			'label' => 'Legs',
			'name' => 'leggings',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47917 => 'Knight / Beigarth\'s',
				47938 => 'Celestial / Wupwup',
				47956 => 'Carrion / Occam\'s',
				47974 => 'Rabid / Ferratus\'s',
				47992 => 'Dire / Morbach',
				48010 => 'Cleric / Tateos',
				48028 => 'Magi / Hronk\'s',
				48046 => 'Apothecary / Veldrunner',
				48064 => 'Valkyrie / Gobrech\'s',
				48082 => 'Berserker / Zojja\'s',
				49619 => 'Zealot / Keeper',
				48100 => 'Soldier / Ahamid',
				84296 => 'Harrier / Zehtuka',
				48118 => 'Rampager / Forgemaster',
				48154 => 'Settler / Leftpaw\'s',
				48190 => 'Shaman / Zintl',
				48136 => 'Assassin / Saphir',
				48172 => 'Cavalier / Angchu',
				66367 => 'Nomad / Ventari',
				73392 => 'Trailblazer / Pahua',
				70414 => 'Minstrel / Maklain',
				87806 => 'Plaguedoctor / Nerashi',
				75183 => 'Marauder / Svaard',
				73234 => 'Crusader / Ossa',
				72719 => 'Wanderer / Ruka',
				71570 => 'Vigilant / Laranthir',
				48208 => 'Sentinel / Wei Qi',
				67450 => 'Sinister / Verata',
				76139 => 'Commander / Tizlak',
				85352 => 'Grieving / The Twins',
				75378 => 'Viper / Yassith',
				85180 => 'Marshal / Nadijeh',
				80664 => 'Seraph / Thackeray',
				89452 => 'diviner / steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c83db11dd588',
			'label' => 'boots',
			'name' => 'boots',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47921 => 'Knight / Beigarth\'s',
				47934 => 'Celestial / Wupwup',
				47952 => 'Carrion / Occam\'s',
				47970 => 'Rabid / Ferratus\'s',
				47988 => 'Dire / Morbach',
				48006 => 'Cleric / Tateos',
				48024 => 'Magi / Hronk',
				48042 => 'Apothecary / Veldrunner',
				48060 => 'Valkyrie / Gobrech',
				48078 => 'Berserker / Zojja',
				49623 => 'Zealot / Keeper',
				48096 => 'Soldier / Ahamid',
				85317 => 'Harrier / Zehtuka',
				48114 => 'Rampager / Forgemaster',
				48150 => 'Settler	Leftpaw',
				48186 => 'Shaman / Zintl',
				48132 => 'Saphir / Armor',
				48168 => 'Cavalier / Angchu',
				66371 => 'Nomad / Ventari',
				72816 => 'Trailblazer / Pahua',
				75349 => 'Minstrel / Maklain',
				87696 => 'Plaguedoctor / Nerashi',
				72251 => 'Marauder / Svaard',
				73766 => 'Crusader / Ossa',
				71242 => 'Wanderer / Ruka',
				72369 => 'Vigilant / Laranthir',
				48204 => 'Sentinel / Wei Qi',
				67454 => 'Sinister / Verata',
				72663 => 'Commander / Tizlak',
				85007 => 'Grieving / The Twins',
				74264 => 'Viper / Yassith',
				85342 => 'Marshal / Nadijeh',
				80491 => 'Seraph / Thackeray',
				89452 => 'diviner / steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:elementalist',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:necromancer',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:mesmer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c7afa9d4e749',
	'title' => 'Medium Armor (new)',
	'fields' => array(
		array(
			'key' => 'field_5c7afb04e7862',
			'label' => 'Medium Helm',
			'name' => 'helm',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47912 => 'Beigarth\'s / Knight',
				47943 => 'Wupwup / Celestial',
				47961 => 'Occam\'s / Carrion',
				47979 => 'Ferratus\'s / Rabid',
				47997 => 'Morbachs / Dire',
				48015 => 'Tateos\'s / Clerics',
				48033 => 'Hronk\'s / Magi',
				48051 => 'Veldrunner / apothecary',
				48069 => 'Gobrech\'s / Valkyrie',
				48087 => 'Zojja\'s / Berserker',
				49614 => 'Keeper\'s / Zealot',
				48105 => 'Ahamid\'s / Soldier',
				85161 => 'Zehtuka\'s / Harrier',
				48123 => 'Forgemaster\'s / rampager',
				48159 => 'Leftpaw\'s / settler',
				48195 => 'Zintl / Shaman',
				48141 => 'Saphir\'s / Assasin',
				48177 => 'Anghu / Cavalier',
				66362 => 'Ventari / Nomad',
				75285 => 'Pahua / Trailblazer',
				75022 => 'Maklain\'s / Minstrel',
				87805 => 'Nerashi / Plaguedoctor',
				77057 => 'Svaard / Marauder',
				74004 => 'Ossa\'s / Crusader',
				74331 => 'Ruka\'s /Wanderer',
				74667 => 'Laranthirs / Vigilant',
				48213 => 'Wei Qi\'s / Sentinel',
				67445 => 'Verata\'s / Sinister',
				70471 => 'Tizlak\'s / Commander',
				85067 => 'The Twins\' / Grieving',
				74357 => 'Yassith\'s / Viper',
				84883 => 'Nadijeh\'s / Marshal',
				80370 => 'Thackeray\'s / Seraph',
				89969 => 'Steelstar\'s / Diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7b2208db1f5',
			'label' => 'medium shoulders',
			'name' => 'shoulders',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47910 => 'Knight / Beigarths',
				47945 => 'Celestial / Wupwup',
				47963 => 'Carrion / Occam\'s',
				47981 => 'Rabid /Ferratus\'s',
				47999 => 'Dire / Morbach\'s',
				48017 => 'Cleric / Tateos\'s',
				48035 => 'Magi /Hronk\'s',
				48053 => 'Apothecary /	Veldrunner',
				48071 => 'Valkyrie / Gobrech\'s',
				48089 => 'Berserker / Zojja\'s',
				49612 => 'Zealot /	Keeper\'s',
				48107 => 'Soldier / Ahamid\'s',
				85172 => 'Harrier / Zehtuka\'s',
				48125 => 'Rampager / Forgemaster\'s',
				48161 => 'Settler / Leftpaw\'s',
				48197 => 'Shaman / Zintl',
				48143 => 'Assasin / Saphir\'s',
				48179 => 'Cavelier / Angchu',
				66360 => 'Nomad / Ventari\'s',
				75572 => 'trailblazer / Pahua\'s',
				76658 => 'Minstrel / Maklain\'s',
				87859 => 'Plaguedoctor / Nerashi\'s',
				75589 => 'Marauder / Svaard\'s',
				73932 => 'Crusader / Ossa\'s',
				73613 => 'Wanderer / Ruka\'s',
				71941 => 'Vigilant / Laranthir\'s',
				48215 => 'Sentinel / Wei Qi\'s',
				67443 => 'Sinister / Verata\'s',
				73971 => 'Commander / Tizlak\'s',
				85054 => 'Grieving / The Twins\'',
				72259 => 'Viper / Yassith\'s',
				85226 => 'Marshal / Nadijeh\'s',
				80137 => 'Seraph / Thackeray\'s',
				89789 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7e5e0cc5ae1',
			'label' => 'Medium coat',
			'name' => 'chest',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47914 => 'Knight	/ Beigarth\'s',
				47941 => 'Wupwup / Celestial',
				47959 => 'Carrion / Occam\'s',
				47977 => 'Rabid / Ferratus\'s',
				47995 => 'Dire / Morbach\'s',
				48013 => 'Cleric / Tateos\'s',
				48031 => 'Magi / Hronk\'s',
				48049 => 'Apothecary / Veldrunner',
				48067 => 'Valkyrie / Gobrech\'s',
				48085 => 'Berserker / Zojja\'s',
				49616 => 'Zealot / Keeper\'s',
				48103 => 'Soldier / Ahamid\'s',
				84923 => 'Harrier / Zehtuka\'s',
				48121 => 'Rampager / Forgemaster\'s',
				48157 => 'Settler /Leftpaw\'s',
				48193 => 'Shaman / Zintl',
				48139 => 'Assasin / Saphir\'s',
				48175 => 'Cavalier / Angchu',
				66364 => 'Nomad / Ventari\'s',
				72341 => 'Trailblazer / Pahua\'s',
				70834 => 'Minstrel / Maklain\'s',
				87985 => 'Plaguedoctor / Nerashi\'s',
				73339 => 'Marauder / Svaard\'s',
				75912 => 'Crusader / Ossa\'s',
				73652 => 'Vigilant / Laranthir\'s',
				48211 => 'Sentinel / Wei Qi\'s',
				67447 => 'Sinister / Verata\'s',
				76110 => 'Commander / Tizlak\'s',
				85062 => 'Grieving / The Twins\'',
				76710 => 'Viper / Yassith\'s',
				85083 => 'Marshal / Nadijeh\'s',
				80280 => 'Seraph / Thackeray\'s',
				89528 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7e6f24cee5c',
			'label' => 'Medium Gloves',
			'name' => 'gloves',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47913 => 'Knight / Beigarths',
				47942 => 'Wupwup / Celestial',
				47960 => 'Carrion / Occam\'s',
				47978 => 'Rabid / Ferratus\'s',
				47996 => 'Dire / Morbach\'s',
				48014 => 'Cleric / Tateos\'s',
				48032 => 'Magi / Hronk\'s',
				48050 => 'Apothecary / Veldrunner',
				48068 => 'Valkyrie / Gobrech\'s',
				48086 => 'Berserker / Zojja\'s',
				49615 => 'Zealot / Keeper\'s',
				48104 => 'Soldier / Ahamid\'s',
				84983 => 'Harrier / Zehtuka\'s',
				48122 => 'Rampager / Forgemaster\'s',
				48158 => 'Settler / Leftpaw\'s',
				48194 => 'Shaman / Zintl',
				48140 => 'Assassin / Saphir\'s',
				48176 => 'Cavalier / Angchu',
				66363 => 'Nomad / Ventari\'s',
				72456 => 'Trailblazer / Pahua\'s',
				76729 => 'Minstrel / Maklain\'s',
				87751 => 'Plaguedoctor / Nerashi\'s',
				75718 => 'Marauder /	Svaard\'s',
				71817 => 'Crusader / Ossa\'s',
				70720 => 'Wanderer / Ruka\'s',
				73090 => 'Vigilant / Laranthir\'s',
				48212 => 'Sentinel / Wei Qi\'s',
				67446 => 'Sinister / Verata\'s',
				76698 => 'Commander / Tizlak\'s',
				85208 => 'Grieving / The Twins\'',
				75626 => 'Viper / Yassith\'s',
				85154 => 'Marshal / Nadijeh\'s',
				80588 => 'Seraph / Thackeray\'s',
				89985 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7e8f5c7d737',
			'label' => 'Medium legs',
			'name' => 'leggings',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': Empty' => ': Empty',
				47911 => 'Knight / Beigarths',
				47944 => 'Wupwup / Celestial',
				47962 => 'Carrion / Occam\'s',
				47980 => 'Rabid / Ferratus\'s',
				47998 => 'Dire / Morbach\'s',
				48016 => 'Cleric / Tateos\'s',
				48034 => 'Magi / Hronk\'s',
				48052 => 'Apothecary / Veldrunner',
				48070 => 'Valkyrie / Gobrech\'s',
				48088 => 'Berserker / Zojja\'s',
				49613 => 'Zealot / Keeper\'s',
				48106 => 'Soldier / Ahamid\'s',
				85149 => 'Harrier / Zehtuka\'s',
				48124 => 'Rampager / Forgemaster\'s',
				48160 => 'Settler / Leftpaw\'s',
				48196 => 'Shaman / Zintl',
				48142 => 'Assassin / Saphir\'s',
				48178 => 'Cavalier / Angchu',
				66361 => 'Nomad / Ventari\'s',
				73395 => 'Trailblazer / Pahua\'s',
				75340 => 'Minstrel / Maklain\'s',
				88025 => 'Plaguedoctor / Nerashi\'s',
				70848 => 'Marauder / Svaard\'s',
				75583 => 'Crusader / Ossa\'s',
				72765 => 'Wanderer / Ruka\'s',
				77150 => 'Vigilant / Laranthir\'s',
				48214 => 'Sentinel / Wei Qi\'s',
				67444 => 'Sinister / Verata\'s',
				73649 => 'Commander / Tizlak\'s',
				85324 => 'Grieving / The Twins\'',
				70641 => 'Viper / Yassith\'s',
				85021 => 'Marshal / Nadijeh\'s',
				80637 => 'Seraph / Thackeray\'s',
				89934 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7fda1c37088',
			'label' => 'boots',
			'name' => 'boots',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47915 => 'Knight / Beigarths',
				47940 => 'Wupwup / Celestial',
				47958 => 'Carrion / Occam\'s',
				47976 => 'Rabid / Ferratus\'s',
				47994 => 'Dire / Morbach\'s',
				48012 => 'Cleric / Tateos\'s',
				48030 => 'Magi / Hronk\'s',
				48048 => 'Apothecary/ Veldrunner',
				48066 => 'Valkyrie / Gobrech\'s',
				48084 => 'Berserker / Zojja\'s',
				49617 => 'Zealot / Keeper\'s',
				48102 => 'Soldier / Ahamid\'s',
				85343 => 'Harrier / Zehtuka\'s',
				48120 => 'Rampager / Forgemaster\'s',
				48156 => 'Settler / Leftpaw\'s',
				48192 => 'Shaman / Zintl',
				48138 => 'Assassin / Saphir\'s',
				48174 => 'Cavalier / Angchu',
				66365 => 'Nomad / Ventari\'s',
				75248 => 'Trailblazer / Pahua\'s',
				77204 => 'Minstrel / Maklain\'s',
				87629 => 'Plaguedoctor / Nerashi\'s',
				74737 => 'Marauder / Svaard\'s',
				74751 => 'Crusader / Ossa\'s',
				70470 => 'Wanderer / Ruka\'s',
				72998 => 'Vigilant / Laranthir\'s',
				48210 => 'Sentinel / Wei Qi\'s',
				67448 => 'Sinister / Verata\'s',
				73835 => 'Commander / Tizlak\'s',
				85308 => 'Grieving / The Twins\'',
				73854 => 'Viper / Yassith\'s',
				84954 => 'Marshal / Nadijeh\'s',
				80300 => 'Serpah / Thackeray\'s',
				89893 => 'Diviner / Steelstars',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:engineer',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:thief',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:ranger',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c77e905997ca',
	'title' => 'New heavy armor',
	'fields' => array(
		array(
			'key' => 'field_5c77e9cc0a904',
			'label' => 'heavy helm',
			'name' => 'helm',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47924 => 'beigarths knight	heavy',
				48003 => 'tateos cleric heavy',
				48021 => 'hronks magi heavy',
				48075 => 'zojjas berserker	heavy',
				48129 => 'saphirs assassin	heavy',
				49626 => 'keepers zealot	heavy',
				66369 => 'ventarisvisor	helm	nomad	heavy',
				67457 => 'veratas sinister	heavy',
				72698 => 'maklains minstrel	heavy',
				74412 => 'yassiths viper	heavy',
				77169 => 'tizlaks commander	heavy',
				80451 => 'thackerays seraph	heavy',
				84879 => 'zehtukas harrier	heavy',
				85274 => 'nadijehsvisor	helm	marshal	heavy',
				85350 => 'thetwinsvisor	helm	grieving	heavy',
				86672 => 'tixxsvisor	helm	giver	heavy',
				89924 => 'steelstars diviner	heavy',
				48057 => 'Valkyrie Gobrech',
				48183 => 'Shaman Zintl',
				47949 => 'Carrion Occam',
				47967 => 'Ferratus Rabid',
				47985 => 'Morbach Dire',
				47931 => 'Wupwup celestial',
				74929 => 'Marauders	Svaard\'s Visor	80	Armor',
				88105 => 'plaguedoctors Nerashi\'s Visor',
				71740 => 'crusaders Ossa\'s Visor	80	Armor',
				70508 => 'wanderer Ruka\'s Visor	80	Armor',
				71424 => 'Vigilant Laranthir\'s Visor	80	Armor',
				48165 => 'Cavalier	Angchu Visor	80	Armor',
				48039 => 'Apothecary Veldrunner Visor	80	Armor',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c792ba3ea50c',
			'label' => 'heavy shoulders',
			'name' => 'shoulders',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47922 => 'Knights Beigarth\'s Pauldrons',
				47933 => 'Celestial Wupwup Pauldrons',
				47951 => 'carrion Occam\'s Pauldrons',
				47969 => 'Rabid Ferratus\'s Pauldrons',
				47987 => 'Dire Morbach\'s Pauldrons',
				48005 => 'Clerics Tateos\'s Pauldrons',
				48023 => 'magi Hronk\'s Pauldrons',
				48041 => 'Apothecary	Veldrunner Pauldrons',
				48059 => 'Valkyrie Gobrech\'s Pauldrons',
				48077 => 'Berserker Zojja\'s Pauldrons',
				49624 => 'Zealot Keeper\'s Pauldrons',
				48095 => 'soldiers Ahamid\'s Pauldrons',
				85286 => 'Harriers Zehtuka\'s Pauldrons',
				48113 => 'Rampager Forgemaster\'s Pauldrons',
				48149 => 'Settlers Leftpaw\'s Pauldrons',
				48185 => 'Shamans Zintl Pauldrons',
				48131 => 'Assassins Saphir\'s Pauldrons',
				48167 => 'Cavalier Angchu Pauldrons',
				66372 => 'Nomad Ventari\'s Pauldrons',
				70630 => 'trailblazer Pahua\'s Pauldrons',
				73009 => 'Minstrel Maklain\'s Pauldrons',
				88073 => 'Plaguedoctors Nerashi\'s Pauldrons',
				76551 => 'Marauders	Svaard\'s Pauldrons',
				75987 => 'Crusaders Ossa\'s Pauldrons',
				72214 => 'Wanderers Ruka\'s Pauldrons',
				74645 => 'Vigilant Laranthir\'s Pauldrons',
				48203 => 'Sentinels Wei Qi\'s Pauldrons',
				67455 => 'Sinister Verata\'s Pauldrons',
				77127 => 'Commanders Tizlak\'s Pauldrons',
				85355 => 'Grieving The Twins\' Pauldrons',
				72557 => 'Vipers Yassith\'s Pauldrons',
				85335 => 'Marshals Nadijeh\'s Pauldrons',
				80616 => 'Seraph Thackeray\'s Pauldrons',
				89785 => 'Diviners steelstars	pauldrons',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7a5e336cb5d',
			'label' => 'heavy coat',
			'name' => 'chest',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47926 => 'Beigarth / Knights',
				47929 => 'Wupwup / Celestial',
				47947 => 'Occam\'s / Carrion',
				47965 => 'Ferratus\'s / Rabid',
				47983 => 'Morbach\'s / Dire',
				48001 => 'Tateos\'s / Clerics',
				48019 => 'Hronk\'s / Magi',
				48037 => 'Veldrunner / Apothecary',
				48055 => 'Gobrech\'s / Valkyrie',
				48073 => 'Zojja\'s / Berserker',
				49627 => 'Keeper\'s / Zealot',
				48091 => 'Ahamid\'s / Soldier',
				85126 => 'Zehtuka\'s / Harrier',
				48109 => 'Forgemaster\'s / Rampager',
				48145 => 'Leftpaw\'s / Settlers',
				48181 => 'Zintl / Shaman',
				48127 => 'Saphir\'s / Assasin',
				48163 => 'Angchu / Cavalier',
				66375 => 'Ventari\'s / Nomad',
				76908 => 'Pahua\'s / Trailblazer',
				70794 => 'Maklain\'s / Minstrel',
				87650 => 'Nerashi\'s / Plaguedoctor',
				76245 => 'Svaard\'s / Marauder',
				76420 => 'Ossa\'s / Crusader',
				76814 => 'Ruka\'s / Wanderer',
				77229 => 'Laranthir\'s / Vigilant',
				48199 => 'Wei Qi\'s / Sentinels',
				67459 => 'Verata\'s / Sinister',
				75107 => 'Tizlak\'s / Commander',
				85042 => 'The Twins\' / Grieving',
				76377 => 'Yassith\'s / Viper',
				85223 => 'Nadijeh\'s / Marshal',
				80280 => 'Thackeray\'s / Seraph',
				89733 => 'Steelstars / Diviners',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7a798b1ceb6',
			'label' => 'Heavy gloves',
			'name' => 'gloves',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47925 => 'Beigarth\'s / Knight',
				47930 => 'Wupwup / Celestial',
				47948 => 'Occam\'s / Carrion',
				47966 => 'Ferratus\'s / Rabid',
				47984 => 'Morbach\'s / Dire',
				48002 => 'Tateos\'s / Cleric',
				48020 => 'Hronk\'s / Magi',
				48038 => 'Veldrunner / Apothecary',
				48056 => 'Gobrech\'s / Valkyrie',
				48074 => 'Zojja\'s / Berserker',
				49611 => 'Keeper\'s / Zealot',
				48092 => 'Ahamid\'s / Soldier',
				85330 => 'Zehtuka\'s / Harriers',
				48110 => 'Forgemaster\'s / Rampagers',
				48146 => 'Leftpaw\'s / Settlers',
				48182 => 'Zintl / Shaman',
				48128 => 'Saphir\'s / Assassin',
				48164 => 'Angchu / Cavalier',
				66374 => 'Ventari\'s / Nomad',
				73697 => 'Pahua\'s / Trailblazers',
				75142 => 'Maklain\'s / Minstrels',
				87887 => 'Nerashi\'s / Plaguedoctor',
				75858 => 'Svaard\'s / Marauder',
				76092 => 'Ossa\'s / Crusader',
				73782 => 'Ruka\'s / Wanderer',
				75554 => 'Laranthir\'s / Vigilant',
				48200 => 'Wei Qi\'s / Sentinel',
				67458 => 'Verata\'s / Sinister',
				77249 => 'Tizlak\'s / Commander',
				85300 => 'The Twins\' / Grieving',
				76776 => 'Yassith\'s / Viper',
				85225 => 'Nadijeh\'s / Marshal',
				80227 => 'Thackeray\'s / Seraph',
				89822 => 'Steelstars / Diviners',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7a85cd05171',
			'label' => 'heavy legs',
			'name' => 'leggings',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47923 => 'Beigarth\'s / Knight',
				47932 => 'Wupwup / Celestial',
				47950 => 'Occam\'s / carrion',
				47968 => 'Ferratus\'s / Rabid',
				47986 => 'Morbach\'s / Dire',
				48004 => 'Tateos\'s / Cleric',
				48022 => 'Hronk\'s / Magi',
				48040 => 'Veldrunner / Apothecary',
				48058 => 'Gobrech\'s / Valkyrie',
				48076 => 'Zojja\'s / Berserker',
				49625 => 'Keeper\'s / Zealot',
				48094 => 'Ahamid\'s / Soldier',
				85024 => 'Zehtuka\'s / Harrier',
				48112 => 'Forgemaster\'s / Rampager',
				48148 => 'Leftpaw\'s / Settler',
				48184 => 'Zintl / Shaman',
				48130 => 'Saphir\'s / Assassin',
				48166 => 'Angchu / Cavalier',
				66373 => 'Ventari\'s / nomad',
				71735 => 'Pahua\'s / trailblazer',
				77022 => 'Maklain\'s / Minstrel',
				88003 => 'Nerashi\'s / Plaguedoctor',
				74962 => 'Svaard\'s / Marauder',
				73719 => 'Ossa\'s / Crusader',
				72496 => 'Ruka\'s/ Wanderer',
				72139 => 'Laranthir\'s / Vigilant',
				48202 => 'Wei Qi\'s / Sentinel',
				67456 => 'Verata\'s / Sinister',
				71249 => 'Tizlak\'s / Commander',
				84911 => 'The Twins\' / Grieving',
				77143 => 'Yassith\'s / Viper',
				85071 => 'Nadijeh\'s / Marshals',
				80274 => 'Thackeray\'s / Seraph',
				89460 => 'steelstars / Diviners',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c7a9b9305172',
			'label' => 'Boots',
			'name' => 'boots',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				47927 => 'Beigarth\'s / Knight',
				47928 => 'Wupwup / Celestial',
				47946 => 'Occam\'s / Carrion',
				47964 => 'Ferratus\'s / Rabid',
				47982 => 'Morbach\'s / Dire',
				48000 => 'Tateos\'s / Cleric',
				48018 => 'Hronk\'s / Magi',
				48036 => 'Veldrunner / apothecary',
				48054 => 'Gobrech\'s / Valkyrie',
				48072 => 'Zojja\'s / Berserker',
				49628 => 'Keeper\'s / Zealot',
				48090 => 'Ahamid\'s / Soldier',
				85196 => 'Zehtuka\'s / Harrier',
				48108 => 'Forgemaster\'s / Rampager',
				48144 => 'Leftpaw\'s / Settler',
				48180 => 'Zintl / Shaman',
				48126 => 'Saphir\'s / Assasin',
				48162 => 'Angchu / Cavelier',
				66368 => 'Ventari\'s / Nomad',
				76263 => 'Pahua\'s / Trailblazer',
				71456 => 'Maklain\'s / Minstrel',
				87742 => 'Nerashi\'s / Plaguedoctor',
				70593 => 'Svaard\'s / Marauder',
				72690 => 'Ossa\'s / Crusader',
				76942 => 'Ruka\'s / Wanderer',
				72190 => 'Laranthir\'s / Vigilant',
				48198 => 'Wei Qi\'s / Sentinel',
				67451 => 'Verata\'s / Sinister',
				72466 => 'Tizlak\'s / Commander',
				85093 => 'The Twins\' / Grieving',
				72548 => 'Yassith\'s / Viper',
				85041 => 'Nadijeh\'s / Marshal',
				80132 => 'Thackeray\'s / Seraph',
				89656 => 'Steelstars / Diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:warrior',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:guardian',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:revenant',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c6c151549143',
	'title' => 'weapons-update',
	'fields' => array(
		array(
			'key' => 'field_5c6c152fd49bf',
			'label' => 'mainweap1',
			'name' => 'mainweap1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'greatsword' => 'Greatsword',
				'sword' => 'Sword',
				'hammer' => 'hammer',
				'mace' => 'Mace',
				'scepter' => 'Scepter',
				'staff' => 'Staff',
				'dagger' => 'Dagger',
				'pistol' => 'Pistol',
				'rifle' => 'Rifle',
				'shortbow' => 'Shortbow',
				'longbow' => 'Longbow',
				'axe' => 'Axe',
				'focus' => 'Focus',
				'shield' => 'Shield',
				'warhorn' => 'Warhorn',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1850d49c0',
			'label' => 'greatsword',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'greatsword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46762 => 'zojjas / berserker',
				49884 => 'keepers / zealot',
				46800 => 'Stonecleavers / Valkyrie',
				46990 => 'Soldier / Chorben',
				46819 => 'beigarths / knight',
				47047 => 'soross / assassin',
				46781 => 'Rampager	Coalforge',
				46933 => 'Cavalier	Angchu',
				66685 => 'ventaris / nomad',
				46914 => 'Settler	Leftpaw',
				46876 => 'Sentinel	Tonn',
				46857 => 'Shaman	Zintl',
				85121 => 'zehtukas / harrier',
				67950 => 'veratas / sinister',
				46838 => 'Carrion	Occam',
				46952 => 'Rabid	Grizzlemouth',
				47066 => 'Dire	Mathilde',
				72314 => 'tizlaks / commander',
				73514 => 'Marauder	Svaard',
				73996 => 'Vigilant	Laranthir',
				75009 => 'Crusader	Ossa',
				75307 => 'Wanderer	Ruka',
				85019 => 'thetwins / grieving',
				71007 => 'yassiths / viper',
				85222 => 'nadijehs / marshal',
				80226 => 'thackerays /seraph',
				76055 => 'Trailblazer	Pahua',
				76501 => 'maklains / minstrel',
				87604 => 'Plaguedoctor	Nerashi',
				47028 => 'theodosuss / cleric',
				46971 => 'hronks / magi',
				86594 => 'tixxs /giver',
				46895 => 'Apothecary	Ebonmane',
				47009 => 'Celestial	Wupwup',
				89706 => 'steelstars / diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1b8fd49c1',
			'label' => 'swords',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas / berserker',
				46831 => 'beigarthsblade sword knight',
				46983 => 'hronksblade sword magi',
				47040 => 'theodosussblade sword cleric',
				47059 => 'sorossblade sword assassin',
				49879 => 'keepersblade sword zealot',
				66672 => 'ventarisblade sword nomad',
				67938 => 'veratasblade sword sinister',
				70838 => 'yassithsblade sword viper',
				73724 => 'tizlaksblade	sword commander',
				76730 => 'maklainsblade sword minstrel',
				84876 => 'thetwinsblade sword grieving',
				84939 => 'zehtukasblade sword harrier',
				85008 => 'nadijehsblade sword marshal',
				86662 => 'tixxsblade sword giver',
				89645 => 'steelstarsblade sword diviner',
				46812 => 'Valkyrie Stonecleaver',
				47002 => 'Soldier Chorben',
				46793 => 'Rampager Coalforge',
				46945 => 'Cavalier Angchu',
				46926 => 'Settler	Leftpaw',
				46888 => 'Sentinel Tonn',
				46869 => 'Shaman Zintl',
				46850 => 'Carrion Occam',
				46964 => 'Rabid Grizzlemouth',
				47078 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				74064 => 'Vigilant Laranthir',
				73373 => 'Crusader Ossa',
				72079 => 'Wanderer Ruka',
				73984 => 'Trailblazer Pahua',
				87885 => 'Plaguedoctor Nerashi',
				46907 => 'Apothecary Ebonmane',
				47021 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1eb01cf58',
			'label' => 'Maces',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'mace',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46766 => 'zojjasflangedmace	mace	berserker',
				46823 => 'beigarthsflangedmace	mace	knight',
				46975 => 'hronksflangedmace	mace	magi',
				47032 => 'theodosussflangedmace	mace	cleric',
				47051 => 'sorossflangedmace	mace	assassin',
				49888 => 'keepersflangedmace	mace	zealot',
				66681 => 'ventarisflangedmace	mace	nomad',
				67946 => 'veratasflangedmace	mace	sinister',
				71457 => 'maklainsflangedmace	mace	minstrel',
				76786 => 'yassithsflangedmace	mace	viper',
				76988 => 'tizlaksflangedmace	mace	commander',
				80624 => 'thackeraysgavel	mace	seraph',
				84912 => 'zehtukasflangedmace	mace	harrier',
				85166 => 'nadijehsflangedmace	mace	marshal',
				85295 => 'thetwinsflangedmace	mace	grieving',
				86504 => 'tixxsflangedmace	mace	giver',
				89707 => 'steelstars diviner',
				46804 => 'Valkyrie Stonecleaver',
				46994 => 'Soldier Chorben',
				46785 => 'Rampager Coalforge',
				46937 => 'Cavalier Angchu',
				46918 => 'Settlers Leftpaw',
				46880 => 'Sentinel Tonn',
				46861 => 'Shaman Zintl',
				46842 => 'Carrion Occam',
				46956 => 'Rabid Grizzlemouth',
				47070 => 'Dire Mathilde',
				75559 => 'Marauder Svaard',
				73631 => 'Vigilant Laranthir',
				75581 => 'Crusader Ossa',
				73487 => 'Wanderer Ruka",',
				71472 => 'Trailblazer Pahua',
				87739 => 'Plaguedoctors Nerashi',
				46899 => 'Apothecary Ebonmane',
				47013 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c209b996f4',
			'label' => 'scepters',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'scepter',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46769 => 'zojjaswand	scepter	berserker',
				46826 => 'beigarthswand	scepter	knight',
				46978 => 'hronkswand	scepter	magi',
				47035 => 'theodosusswand	scepter	cleric',
				47054 => 'sorosswand	scepter	assassin',
				49891 => 'keeperswand	scepter	zealot',
				66674 => 'ventariswand	scepter	nomad',
				67943 => 'verataswand	scepter	sinister',
				73220 => 'maklainswand	scepter	minstrel',
				76688 => 'yassithswand	scepter	viper',
				76821 => 'tizlakswand	scepter	commander',
				85027 => 'zehtukaswand	scepter	harrier',
				85076 => 'thetwinswand	scepter	grieving',
				85109 => 'nadijehswand	scepter	marshal',
				86443 => 'tixxswand	scepter	giver',
				89484 => 'steelstarswand	scepter	diviner'
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c21d38041a',
			'label' => 'Staffs',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'staff',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46773 => 'zojjasspire	staff	berserker',
				46830 => 'beigarthsspire	staff	knight',
				46982 => 'hronksspire	staff	magi',
				47039 => 'theodosussspire	staff	cleric',
				47058 => 'sorossspire	staff	assassin',
				49878 => 'keepersspire	staff	zealot',
				66680 => 'ventarisspire	staff	nomad',
				67939 => 'veratasspire	staff	sinister',
				71387 => 'yassithsspire	staff	viper',
				75200 => 'maklainsspire	staff	minstrel',
				76089 => 'tizlaksspire	staff	commander',
				85001 => 'thetwinsspire	staff	grieving',
				85112 => 'zehtukasspire	staff	harrier',
				85356 => 'nadijehsspire	staff	marshal',
				86561 => 'tixxsspire	staff	giver',
				89945 => 'steelstarsspire	staff	diviner',
				46811 => 'Valkyrie Stonecleaver',
				47001 => 'Soldier Chorben',
				46792 => 'Rampager Coalforge',
				46944 => 'Cavalier Angchu',
				46925 => 'Settler Leftpaw',
				46887 => 'Sentinel Tonn',
				46868 => 'Shaman Zintl',
				46849 => 'Carrion Occam',
				46963 => 'Rabid Grizzlemouth',
				47077 => 'Dire Mathilde',
				76889 => 'Marauder Svaard',
				76631 => 'Vigilant Laranthir',
				70416 => 'Crusader Ossa',
				74735 => 'Wanderer Ruka',
				72927 => 'Trailblazer Pahua',
				87785 => 'Plaguedoctor Nerashi',
				46906 => 'Apothecary Ebonmane',
				47020 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c23209f368',
			'label' => 'daggers',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c25928b116',
			'label' => 'Pistol',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol diviner',
				46805 => 'Valkyrie Stonecleaver',
				46995 => 'Soldier Chorben',
				46786 => 'Rampager Coalforge',
				46938 => 'Cavalier Angchu',
				46919 => 'Settler	Leftpaw',
				46881 => 'Sentinel Tonn',
				46862 => 'Shaman Zintl',
				46843 => 'Carrion Occam',
				46957 => 'Rabid Grizzlemouth',
				47071 => 'Dire Mathilde',
				70482 => 'Marauder Svaard',
				74612 => 'Vigilant Laranthir',
				73925 => 'Crusader Ossa',
				72108 => 'Wanderer Ruka',
				72860 => 'Trailblazer Pahua',
				88047 => 'Plaguedoctor Nerashi',
				46900 => 'Apothecary Ebonmane',
				47014 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c263265550',
			'label' => 'Rifle',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'rifle',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46768 => 'zojjasmusket	rifle	berserker',
				46825 => 'beigarthsmusket	rifle	knight',
				46977 => 'hronksmusket	rifle	magi',
				47034 => 'theodosussmusket	rifle	cleric',
				47053 => 'sorossmusket	rifle	assassin',
				49890 => 'keepersmusket	rifle	zealot',
				66679 => 'ventarismusket	rifle	nomad',
				67952 => 'veratasmusket	rifle	sinister',
				71219 => 'tizlaksmusket	rifle	commander',
				72279 => 'yassithsmusket	rifle	viper',
				73497 => 'maklainsmusket	rifle	minstrel',
				84886 => 'nadijehsmusket	rifle	marshal',
				85072 => 'thetwinsmusket	rifle	grieving',
				85348 => 'zehtukasmusket	rifle	harrier',
				89736 => 'steelstarsmusket	rifle	diviner',
				46806 => 'Valkyrie Stonecleaver',
				46996 => 'Soldier Chorben',
				46787 => 'Rampager Coalforge',
				46939 => 'Cavalier Angchu',
				46920 => 'Settler Leftpaw',
				46882 => 'Sentinel Tonn',
				46863 => 'Shaman Zintl',
				46844 => 'Carrion Occam',
				46958 => 'Rabid Grizzlemouth',
				47072 => 'Dire Mathilde',
				71478 => 'Marauder Svaard',
				73357 => 'Vigilant Laranthir',
				70729 => 'Crusader Ossa',
				77055 => 'Wanderer Ruka',
				76984 => 'Trailblazer Pahua',
				87956 => 'Plaguedoctor Nerashi',
				46901 => 'Apothecary Ebonmane',
				47015 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2730a4eda',
			'label' => 'Shortbow',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'shortbow',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46771 => 'zojjas berserker',
				46828 => 'beigarths knight',
				46980 => 'hronks magi',
				47037 => 'theodosuss cleric',
				47056 => 'soross assassin',
				49876 => 'keepers zealot',
				66676 => 'ventaris nomad',
				67941 => 'veratas sinister',
				74083 => 'tizlaks commander',
				74569 => 'yassiths viper',
				75644 => 'maklains minstrel',
				80391 => 'thackerays seraph',
				85156 => 'nadijehs marshal',
				85200 => 'zehtukas harrier',
				85242 => 'thetwins grieving',
				86706 => 'tixxs giver',
				89949 => 'steelstars diviner',
				46809 => 'Valkyrie Stonecleaver',
				46999 => 'Soldier Chorben',
				46790 => 'Rampager Coalforge',
				46942 => 'Cavalier Angchu',
				46923 => 'Settler Leftpaw',
				46885 => 'Sentinel Tonn',
				46866 => 'Shaman Zintl',
				46847 => 'Carrion Occam',
				46961 => 'Rabid Grizzlemouth',
				47075 => 'Dire Mathilde',
				73280 => 'Marauder Svaard',
				76878 => 'Vigilant Laranthir',
				71645 => 'Crusader Ossa',
				75743 => 'Wanderer Ruka',
				76256 => 'Trailblazer Pahua',
				87811 => 'Plaguedoctor Nerashi',
				46904 => 'Apothecary Ebonmane',
				47018 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c287570535',
			'label' => 'longbow',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'longbow',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46765 => 'zojjas berserker',
				46822 => 'beigarths knight',
				46974 => 'hronksgreatbow	longbow	magi',
				47031 => 'theodosussgreatbow	longbow	cleric',
				47050 => 'sorossgreatbow	longbow	assassin',
				49887 => 'keepersgreatbow	longbow	zealot',
				66682 => 'ventarisgreatbow	longbow	nomad',
				67947 => 'veratasgreatbow	longbow	sinister',
				70504 => 'yassithsgreatbow	longbow	viper',
				73948 => 'maklainsgreatbow	longbow	minstrel',
				74953 => 'tizlaksgreatbow	longbow	commander',
				80402 => 'thackeraysgreatbow	longbow	seraph',
				85073 => 'nadijehsgreatbow	longbow	marshal',
				85111 => 'zehtukasgreatbow	longbow	harrier',
				85212 => 'thetwinsgreatbow	longbow	grieving',
				86483 => 'tixxsgreatbow	longbow	giver',
				89681 => 'steelstarsgreatbow	longbow	diviner',
				46803 => 'Valkyrie Stonecleaver',
				46993 => 'Soldier Chorben',
				46784 => 'Rampager Coalforge',
				46936 => 'Cavalier Angchu',
				46917 => 'Settler Leftpaw',
				46879 => 'Sentinel Tonn',
				46860 => 'Shaman Zintl',
				46841 => 'Carrion Occam',
				46955 => 'Rabid Grizzlemouth',
				47069 => 'Dire Mathilde',
				75747 => 'Marauder Svaard',
				75025 => 'Vigilant Laranthir',
				74935 => 'Crusader Ossa',
				71114 => 'Wanderer Ruka',
				75642 => 'Trailblazer Pahua',
				87866 => 'Plaguedoctor Nerashi',
				46898 => 'Apothecary Ebonmane',
				47012 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c28d3b54bc',
			'label' => 'axe',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'axe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46759 => 'zojjas berserker',
				46816 => 'beigarths knight',
				46968 => 'hronks magi',
				47025 => 'theodosuss cleric',
				47044 => 'soross assassin',
				49880 => 'keepers zealot',
				66673 => 'ventaris nomad',
				67944 => 'veratas sinister',
				72476 => 'tizlaks commander',
				74905 => 'maklains minstrel',
				77122 => 'yassiths viper',
				85047 => 'zehtuka harrier',
				85233 => 'nadijehs marshal',
				85253 => 'thetwins grieving',
				86444 => 'tixxs giver',
				89799 => 'steelstars diviner',
				46797 => 'Valkyrie Stonecleaver',
				46987 => 'Soldier Chorben',
				46778 => 'Rampager Coalforge',
				46930 => 'Cavalier Angchu',
				46911 => 'Settler Leftpaw',
				46873 => 'Sentinel Tonn',
				46854 => 'Shaman Zintl',
				46835 => 'Carrion Occam',
				46949 => 'Rabid Grizzlemouth',
				47063 => 'Dire Mathilde',
				72882 => 'Marauder Svaard',
				75224 => 'Vigilant Laranthir',
				75667 => 'Crusader Ossa',
				74679 => 'Wanderer Ruka',
				71361 => 'Trailblazer Pahua',
				87605 => 'Plaguedoctor Nerashi',
				46892 => 'Apothecary Ebonmane',
				47006 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d547fdc85e',
			'label' => 'hammer',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'hammer',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46763 => 'zojjas berserker',
				46820 => 'beigarths knight',
				46972 => 'hronks magi',
				47029 => 'theodosuss cleric',
				47048 => 'soross assassin',
				49885 => 'keepers zealot',
				66684 => 'ventaris nomad',
				67949 => 'veratas sinister',
				74363 => 'yassiths viper',
				76262 => 'maklains minstrel',
				76977 => 'tizlaks commander',
				80522 => 'thackerays seraph',
				85228 => 'zehtukas harrier',
				85249 => 'thetwins grieving',
				85347 => 'nadijehs marshal',
				86564 => 'tixxs giver',
				89773 => 'steelstars diviner',
				46801 => 'Valkyrie Stonecleaver',
				46991 => 'Soldier Chorben',
				46782 => 'Rampager Coalforge',
				46934 => 'Cavalier Angchu',
				46915 => 'Settler Leftpaw',
				46877 => 'Sentinel Tonn',
				46858 => 'Shaman Zintl',
				46839 => 'Carrion Occam',
				46953 => 'Rabid Grizzlemouth',
				47067 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				75174 => 'Vigilant Laranthir',
				'73298: Crusader Ossa' => '73298: Crusader Ossa',
				75521 => 'Wanderer Ruka',
				74776 => 'Trailblazer Pahua',
				'87671: Plaguedoctor Nerashi' => '87671: Plaguedoctor Nerashi',
				'46896: Apothecary Ebonmane' => '46896: Apothecary Ebonmane',
				47010 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4286b76e2',
			'label' => 'offhand1',
			'name' => 'offhand1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'warhorn :Warhorn' => 'warhorn :Warhorn',
				'Dagger' => 'dagger',
				'axe' => 'axe',
				'shield' => 'shield',
				'torch :Torch' => 'torch :Torch',
				'sword' => 'sword',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4455b76e6',
			'label' => 'swords (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas / berserker',
				46831 => 'beigarthsblade	sword	knight',
				'46983 :	hronksblade	sword	magi' => '46983 :	hronksblade	sword	magi',
				'47040 :	theodosussblade	sword	cleric' => '47040 :	theodosussblade	sword	cleric',
				'47059 :	sorossblade	sword	assassin' => '47059 :	sorossblade	sword	assassin',
				'49879 :	keepersblade	sword	zealot' => '49879 :	keepersblade	sword	zealot',
				'66672 :	ventarisblade	sword	nomad' => '66672 :	ventarisblade	sword	nomad',
				'67938 :	veratasblade	sword	sinister' => '67938 :	veratasblade	sword	sinister',
				'70838 :	yassithsblade	sword	viper' => '70838 :	yassithsblade	sword	viper',
				'73724 :	tizlaksblade	sword	commander' => '73724 :	tizlaksblade	sword	commander',
				'76730 :	maklainsblade	sword	minstrel' => '76730 :	maklainsblade	sword	minstrel',
				'84876 :	thetwinsblade	sword	grieving' => '84876 :	thetwinsblade	sword	grieving',
				'84939 :	zehtukasblade	sword	harrier' => '84939 :	zehtukasblade	sword	harrier',
				'85008 :	nadijehsblade	sword	marshal' => '85008 :	nadijehsblade	sword	marshal',
				'86662 :	tixxsblade	sword	giver' => '86662 :	tixxsblade	sword	giver',
				'89645 :	steelstarsblade	sword	diviner' => '89645 :	steelstarsblade	sword	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4437b76e5',
			'label' => 'Pistol (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4417b76e4',
			'label' => 'axe (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'axe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'46759	zojjasreaver	axe	berserker' => '46759	zojjasreaver	axe	berserker',
				'46816	beigarthsreaver	axe	knight' => '46816	beigarthsreaver	axe	knight',
				'46968	hronksreaver	axe	magi' => '46968	hronksreaver	axe	magi',
				'47025	theodosussreaver	axe	cleric' => '47025	theodosussreaver	axe	cleric',
				'47044	sorossreaver	axe	assassin' => '47044	sorossreaver	axe	assassin',
				'49880	keepersreaver	axe	zealot' => '49880	keepersreaver	axe	zealot',
				'66673	ventarisreaver	axe	nomad' => '66673	ventarisreaver	axe	nomad',
				'67944	veratasreaver	axe	sinister' => '67944	veratasreaver	axe	sinister',
				'72476	tizlaksreaver	axe	commander' => '72476	tizlaksreaver	axe	commander',
				'74905	maklainsreaver	axe	minstrel' => '74905	maklainsreaver	axe	minstrel',
				'77122	yassithsreaver	axe	viper' => '77122	yassithsreaver	axe	viper',
				'85047	zehtukasreaver	axe	harrier' => '85047	zehtukasreaver	axe	harrier',
				'85233	nadijehsreaver	axe	marshal' => '85233	nadijehsreaver	axe	marshal',
				'85253	thetwinsreaver	axe	grieving' => '85253	thetwinsreaver	axe	grieving',
				'86444	tixxsreaver	axe	giver' => '86444	tixxsreaver	axe	giver',
				'89799	steelstarsreaver	axe	diviner' => '89799	steelstarsreaver	axe	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d43f3b76e3',
			'label' => 'daggers (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjasrazor	dagger	berserker',
				46817 => 'beigarthsrazor	dagger	knight',
				46969 => 'hronksrazor	dagger	magi',
				47026 => 'theodosussrazor	dagger	cleric',
				47045 => 'sorossrazor	dagger	assassin',
				49882 => 'keepersrazor	dagger	zealot',
				66687 => 'ventarisrazor	dagger	nomad',
				67948 => 'veratasrazor	dagger	sinister',
				73059 => 'tizlaksrazor	dagger	commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehsrazor	dagger	marshal',
				84936 => 'thetwinsrazor	dagger	grieving',
				85051 => 'zehtukasrazor	dagger	harrier',
				86085 => 'marshalsstellarrazor	dagger	marshal',
				86689 => 'tixxsrazor	dagger	giver',
				89906 => 'steelstarsrazor	dagger	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c292e714df',
			'label' => 'focus',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'focus',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'46761	zojjasartifact	focus	berserker' => '46761	zojjasartifact	focus	berserker',
				'46818	beigarthsartifact	focus	knight' => '46818	beigarthsartifact	focus	knight',
				'46970	hronksartifact	focus	magi' => '46970	hronksartifact	focus	magi',
				'47027	theodosussartifact	focus	cleric' => '47027	theodosussartifact	focus	cleric',
				'47046	sorossartifact	focus	assassin' => '47046	sorossartifact	focus	assassin',
				'49874	keepersartifact	focus	zealot' => '49874	keepersartifact	focus	zealot',
				'66686	ventarisartifact	focus	nomad' => '66686	ventarisartifact	focus	nomad',
				'67951	veratasartifact	focus	sinister' => '67951	veratasartifact	focus	sinister',
				'71584	yassithsartifact	focus	viper' => '71584	yassithsartifact	focus	viper',
				'72188	maklainsartifact	focus	minstrel' => '72188	maklainsartifact	focus	minstrel',
				'75356	tizlaksartifact	focus	commander' => '75356	tizlaksartifact	focus	commander',
				'85044	thetwinsartifact	focus	grieving' => '85044	thetwinsartifact	focus	grieving',
				'85224	nadijehsartifact	focus	marshal' => '85224	nadijehsartifact	focus	marshal',
				'85346	zehtukasartifact	focus	harrier' => '85346	zehtukasartifact	focus	harrier',
				'86463	tixxsartifact	focus	giver' => '86463	tixxsartifact	focus	giver',
				'89846	steelstarsartifact	focus	diviner' => '89846	steelstarsartifact	focus	diviner',
				'' => '',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2963c1bfc',
			'label' => 'shield',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'shield',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46770 => 'zojjasbastion	shield	berserker',
				46827 => 'beigarthsbastion	shield	knight',
				46979 => 'hronksbastion	shield	magi',
				47036 => 'theodosussbastion	shield	cleric',
				47055 => 'sorossbastion	shield	assassin',
				49875 => 'keepersbastion	shield	zealot',
				66675 => 'ventarisbastion	shield	nomad',
				67942 => 'veratasbastion	shield	sinister',
				71944 => 'yassithsbastion	shield	viper',
				74748 => 'maklainsbastion	shield	minstrel',
				76075 => 'tizlaksbastion	shield	commander',
				84957 => 'zehtukasbastion	shield	harrier',
				85266 => 'thetwinsbastion	shield	grieving',
				85357 => 'nadijehsbastion	shield	marshal',
				86505 => 'tixxsbastion	shield	giver',
				89922 => 'steelstarsbastion	shield	diviner',
				'Valkyrie Stonecleaver' => 'Valkyrie Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				46884 => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				46903 => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2a1ffcc17',
			'label' => 'warhorn',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46777 => 'zojjasherald	warhorn	berserker',
				46834 => 'beigarthsherald	warhorn	knight',
				46986 => 'hronksherald	warhorn	magi',
				47043 => 'theodosussherald	warhorn	cleric',
				47062 => 'sorossherald	warhorn	assassin',
				49883 => 'keepersherald	warhorn	zealot',
				66678 => 'ventarisherald	warhorn	nomad',
				67936 => 'veratasherald	warhorn	sinister',
				71116 => 'maklainsherald	warhorn	minstrel',
				71117 => 'tizlaksherald	warhorn	commander',
				75325 => 'yassithsherald	warhorn	viper',
				84973 => 'zehtukasherald	warhorn	harrier',
				85074 => 'thetwinsherald	warhorn	grieving',
				85116 => 'nadijehs marshal',
				86440 => 'tixxsherald giver',
				89624 => 'steelstars diviner',
				46815 => 'Valkyrie Stonecleaver',
				47005 => 'Soldier Chorben',
				46796 => 'Rampager Coalforge',
				46948 => 'Cavalier Angchu',
				46929 => 'Settler Leftpaw',
				46891 => 'Sentinel Tonn',
				46872 => 'Shaman Zintl',
				46853 => 'Carrion Occam',
				46967 => 'Rabid Grizzlemouth',
				47081 => 'Dire Mathilde',
				75201 => 'Marauder Svaard',
				76824 => 'Vigilant Laranthir',
				71005 => 'Crusader Ossa',
				75042 => 'Wanderer Ruka',
				75697 => 'Trailblazer Pahua',
				87898 => 'Plaguedoctor Nerashi',
				46910 => 'Apothecary Ebonmane',
				47024 => 'Celestial Wupwup',
				80407 => 'thackeray seraph',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d70ae45462',
			'label' => 'Torch',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46775 => 'zojjas berserker',
				'46832: beigarths knight' => '46832: beigarths knight',
				46984 => 'hronks magi',
				47041 => 'theodosuss cleric',
				47060 => 'soross assassin',
				49881 => 'keepers zealot',
				66688 => 'ventaris nomad',
				67937 => 'veratas sinister',
				76271 => 'yassiths viper',
				'75820 maklains minstrel' => '75820 maklains minstrel',
				'75611 tizlaks commander' => '75611 tizlaks commander',
				80683 => 'thackerays seraph',
				85013 => 'zehtukas harrier',
				85006 => 'thetwins grieving',
				85152 => 'nadijehs marshal',
				86439 => 'Tixxs giver',
				89612 => 'steelstars diviner',
				46813 => 'Valkyrie Stonecleaver',
				47003 => 'Soldier Chorben',
				46794 => 'Rampager Coalforge',
				46946 => 'Cavalier Angchu',
				46927 => 'Settler Leftpaw',
				46889 => 'Sentinel Tonn',
				46870 => 'Shaman Zintl',
				46851 => 'Carrion Occam',
				46965 => 'Rabid Grizzlemouth',
				47079 => 'Dire Mathilde',
				74500 => 'Marauder Svaard',
				71161 => 'Vigilant Laranthir',
				72004 => 'Crusader Ossa',
				72893 => 'Wanderer Ruka',
				72256 => 'Trailblazer Pahua',
				'87858: Plaguedoctor Nerashi' => '87858: Plaguedoctor Nerashi',
				46908 => 'Apothecary Ebonmane',
				47022 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de54f534e1',
			'label' => 'mainweap2',
			'name' => 'mainweap2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'greatsword' => 'Greatsword',
				'sword' => 'Sword',
				'hammer' => 'hammer',
				'mace' => 'Mace',
				'scepter' => 'Scepter',
				'staff' => 'Staff',
				'dagger' => 'Dagger',
				'pistol' => 'Pistol',
				'rifle' => 'Rifle',
				'shortbow' => 'Shortbow',
				'longbow' => 'Longbow',
				'axe' => 'Axe',
				'focus' => 'Focus',
				'shield' => 'Shield',
				'warhorn' => 'Warhorn',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de836534e2',
			'label' => 'greatsword (copy)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'greatsword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46762 => 'zojjas / berserker',
				49884 => 'keepers / zealot',
				46800 => 'Stonecleavers / Valkyrie',
				46990 => 'Soldier / Chorben',
				46819 => 'beigarths / knight',
				47047 => 'soross / assassin',
				46781 => 'Rampager	Coalforge',
				46933 => 'Cavalier	Angchu',
				66685 => 'ventaris / nomad',
				46914 => 'Settler	Leftpaw',
				46876 => 'Sentinel	Tonn',
				46857 => 'Shaman	Zintl',
				85121 => 'zehtukas / harrier',
				67950 => 'veratas / sinister',
				46838 => 'Carrion	Occam',
				46952 => 'Rabid	Grizzlemouth',
				47066 => 'Dire	Mathilde',
				72314 => 'tizlaks / commander',
				73514 => 'Marauder	Svaard',
				73996 => 'Vigilant	Laranthir',
				75009 => 'Crusader	Ossa',
				75307 => 'Wanderer	Ruka',
				85019 => 'thetwins / grieving',
				71007 => 'yassiths / viper',
				85222 => 'nadijehs / marshal',
				80226 => 'thackerays /seraph',
				76055 => 'Trailblazer	Pahua',
				76501 => 'maklains / minstrel',
				87604 => 'Plaguedoctor	Nerashi',
				47028 => 'theodosuss / cleric',
				46971 => 'hronks / magi',
				86594 => 'tixxs /giver',
				46895 => 'Apothecary	Ebonmane',
				47009 => 'Celestial Wupwup',
				89706 => 'steelstars / diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de857534e3',
			'label' => 'swords (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas berserker',
				46831 => 'beigarths knight',
				46983 => 'hronks magi',
				47040 => 'theodosuss cleric',
				47059 => 'soross assassin',
				49879 => 'keepers zealot',
				66672 => 'ventaris nomad',
				67938 => 'veratas sinister',
				70838 => 'yassiths viper',
				73724 => 'tizlaks commander',
				76730 => 'maklains minstrel',
				84876 => 'thetwins grieving',
				84939 => 'zehtukas harrier',
				85008 => 'nadijehs marshal',
				86662 => 'tixxs giver',
				89645 => 'steelstars diviner',
				46812 => 'Valkyrie Stonecleaver',
				47002 => 'Soldier Chorben',
				46793 => 'Rampager Coalforge',
				46945 => 'Cavalier Angchu',
				46926 => 'Settler	Leftpaw',
				46888 => 'Sentinel Tonn',
				46869 => 'Shaman Zintl',
				46850 => 'Carrion Occam',
				46964 => 'Rabid Grizzlemouth',
				47078 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				74064 => 'Vigilant Laranthir',
				73373 => 'Crusader Ossa',
				72079 => 'Wanderer Ruka',
				73984 => 'Trailblazer Pahua',
				87885 => 'Plaguedoctor Nerashi',
				46907 => 'Apothecary Ebonmane',
				47021 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de9f0534e4',
			'label' => 'daggers (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6ebe9368eb1',
			'label' => 'Staffs (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'staff',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46773 => 'zojjasspire	staff	berserker',
				46830 => 'beigarthsspire	staff	knight',
				46982 => 'hronksspire	staff	magi',
				47039 => 'theodosussspire	staff	cleric',
				47058 => 'sorossspire	staff	assassin',
				49878 => 'keepersspire	staff	zealot',
				66680 => 'ventarisspire	staff	nomad',
				67939 => 'veratasspire	staff	sinister',
				71387 => 'yassithsspire	staff	viper',
				75200 => 'maklainsspire	staff	minstrel',
				76089 => 'tizlaksspire	staff	commander',
				85001 => 'thetwinsspire	staff	grieving',
				85112 => 'zehtukasspire	staff	harrier',
				85356 => 'nadijehsspire	staff	marshal',
				86561 => 'tixxsspire	staff	giver',
				89945 => 'steelstarsspire	staff	diviner',
				46811 => 'Valkyrie Stonecleaver',
				47001 => 'Soldier Chorben',
				46792 => 'Rampager Coalforge',
				46944 => 'Cavalier Angchu',
				46925 => 'Settler Leftpaw',
				46887 => 'Sentinel Tonn',
				46868 => 'Shaman Zintl',
				46849 => 'Carrion Occam',
				46963 => 'Rabid Grizzlemouth',
				47077 => 'Dire Mathilde',
				76889 => 'Marauder Svaard',
				76631 => 'Vigilant Laranthir',
				70416 => 'Crusader Ossa',
				74735 => 'Wanderer Ruka',
				72927 => 'Trailblazer Pahua',
				87785 => 'Plaguedoctor Nerashi',
				46906 => 'Apothecary Ebonmane',
				47020 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6dea03534e5',
			'label' => 'offhand2',
			'name' => 'offhand2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'warhorn :Warhorn' => 'warhorn :Warhorn',
				'Dagger' => 'dagger',
				'axe' => 'axe',
				'shield' => 'shield',
				'torch :Torch' => 'torch :Torch',
				'sword' => 'sword',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6eb0ecd5d0a',
			'label' => 'Torch (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46775 => 'zojjas berserker',
				'46832: beigarths knight' => '46832: beigarths knight',
				46984 => 'hronks magi',
				47041 => 'theodosuss cleric',
				47060 => 'soross assassin',
				49881 => 'keepers zealot',
				66688 => 'ventaris nomad',
				67937 => 'veratas sinister',
				76271 => 'yassiths viper',
				'75820 maklains minstrel' => '75820 maklains minstrel',
				'75611 tizlaks commander' => '75611 tizlaks commander',
				80683 => 'thackerays seraph',
				85013 => 'zehtukas harrier',
				85006 => 'thetwins grieving',
				85152 => 'nadijehs marshal',
				86439 => 'Tixxs giver',
				89612 => 'steelstars diviner',
				46813 => 'Valkyrie Stonecleaver',
				47003 => 'Soldier Chorben',
				46794 => 'Rampager Coalforge',
				46946 => 'Cavalier Angchu',
				46927 => 'Settler Leftpaw',
				46889 => 'Sentinel Tonn',
				46870 => 'Shaman Zintl',
				46851 => 'Carrion Occam',
				46965 => 'Rabid Grizzlemouth',
				47079 => 'Dire Mathilde',
				74500 => 'Marauder Svaard',
				71161 => 'Vigilant Laranthir',
				72004 => 'Crusader Ossa',
				72893 => 'Wanderer Ruka',
				72256 => 'Trailblazer Pahua',
				'87858: Plaguedoctor Nerashi' => '87858: Plaguedoctor Nerashi',
				46908 => 'Apothecary Ebonmane',
				47022 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6defcc534e7',
			'label' => 'swords (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas / berserker',
				46831 => 'beigarthsblade	sword	knight',
				'46983 :	hronksblade	sword	magi' => '46983 :	hronksblade	sword	magi',
				'47040 :	theodosussblade	sword	cleric' => '47040 :	theodosussblade	sword	cleric',
				'47059 :	sorossblade	sword	assassin' => '47059 :	sorossblade	sword	assassin',
				'49879 :	keepersblade	sword	zealot' => '49879 :	keepersblade	sword	zealot',
				'66672 :	ventarisblade	sword	nomad' => '66672 :	ventarisblade	sword	nomad',
				'67938 :	veratasblade	sword	sinister' => '67938 :	veratasblade	sword	sinister',
				'70838 :	yassithsblade	sword	viper' => '70838 :	yassithsblade	sword	viper',
				'73724 :	tizlaksblade	sword	commander' => '73724 :	tizlaksblade	sword	commander',
				'76730 :	maklainsblade	sword	minstrel' => '76730 :	maklainsblade	sword	minstrel',
				'84876 :	thetwinsblade	sword	grieving' => '84876 :	thetwinsblade	sword	grieving',
				'84939 :	zehtukasblade	sword	harrier' => '84939 :	zehtukasblade	sword	harrier',
				'85008 :	nadijehsblade	sword	marshal' => '85008 :	nadijehsblade	sword	marshal',
				'86662 :	tixxsblade	sword	giver' => '86662 :	tixxsblade	sword	giver',
				'89645 :	steelstarsblade	sword	diviner' => '89645 :	steelstarsblade	sword	diviner',
				46812 => 'Valkyrie	Stonecleaver',
				47002 => 'Soldier	Chorben',
				46793 => 'Rampager	Coalforge',
				46945 => 'Cavalier	Angchu',
				46926 => 'Settler	Leftpaw',
				46888 => 'Sentinel	Tonn',
				46869 => 'Shaman	Zintl',
				46850 => 'Carrion	Occam',
				46964 => 'Rabid	Grizzlemouth',
				47078 => 'Dire	Mathilde',
				75897 => 'Marauder	Svaard',
				74064 => 'Vigilant	Laranthir',
				73373 => 'Crusader	Ossa',
				72079 => 'Wanderer	Ruka',
				73984 => 'Trailblazer	Pahua',
				87885 => 'Plaguedoctor	Nerashi',
				46907 => 'Apothecary	Ebonmane',
				47021 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6def03534e6',
			'label' => 'daggers (offhand 2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassiths viper',
				75388 => 'maklains minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6ea9678e88a',
			'label' => 'warhorn (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46777 => 'zojjasherald	warhorn	berserker',
				46834 => 'beigarthsherald	warhorn	knight',
				46986 => 'hronksherald	warhorn	magi',
				47043 => 'theodosussherald	warhorn	cleric',
				47062 => 'sorossherald	warhorn	assassin',
				49883 => 'keepersherald	warhorn	zealot',
				66678 => 'ventarisherald	warhorn	nomad',
				67936 => 'veratasherald	warhorn	sinister',
				71116 => 'maklainsherald	warhorn	minstrel',
				71117 => 'tizlaksherald	warhorn	commander',
				75325 => 'yassithsherald	warhorn	viper',
				84973 => 'zehtukasherald	warhorn	harrier',
				85074 => 'thetwinsherald	warhorn	grieving',
				85116 => 'nadijehs marshal',
				86440 => 'tixxsherald giver',
				89624 => 'steelstars diviner',
				46815 => 'Valkyrie Stonecleaver',
				47005 => 'Soldier Chorben',
				46796 => 'Rampager Coalforge',
				46948 => 'Cavalier Angchu',
				46929 => 'Settler Leftpaw',
				46891 => 'Sentinel Tonn',
				46872 => 'Shaman Zintl',
				46853 => 'Carrion Occam',
				46967 => 'Rabid Grizzlemouth',
				47081 => 'Dire Mathilde',
				75201 => 'Marauder Svaard',
				76824 => 'Vigilant Laranthir',
				71005 => 'Crusader Ossa',
				75042 => 'Wanderer Ruka',
				75697 => 'Trailblazer Pahua',
				87898 => 'Plaguedoctor Nerashi',
				46910 => 'Apothecary Ebonmane',
				47024 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:builds',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
