if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c6c151549143',
	'title' => 'weapons-update',
	'fields' => array(
		array(
			'key' => 'field_5c6c152fd49bf',
			'label' => 'mainweap1',
			'name' => 'mainweap1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'greatsword' => 'Greatsword',
				'sword' => 'Sword',
				'hammer' => 'hammer',
				'mace' => 'Mace',
				'scepter' => 'Scepter',
				'staff' => 'Staff',
				'dagger' => 'Dagger',
				'pistol' => 'Pistol',
				'rifle' => 'Rifle',
				'shortbow' => 'Shortbow',
				'longbow' => 'Longbow',
				'axe' => 'Axe',
				'focus' => 'Focus',
				'shield' => 'Shield',
				'warhorn' => 'Warhorn',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1850d49c0',
			'label' => 'greatsword',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'greatsword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46762 => 'zojjas / berserker',
				49884 => 'keepers / zealot',
				46800 => 'Stonecleavers / Valkyrie',
				46990 => 'Soldier / Chorben',
				46819 => 'beigarths / knight',
				47047 => 'soross / assassin',
				46781 => 'Rampager	Coalforge',
				46933 => 'Cavalier	Angchu',
				66685 => 'ventaris / nomad',
				46914 => 'Settler	Leftpaw',
				46876 => 'Sentinel	Tonn',
				46857 => 'Shaman	Zintl',
				85121 => 'zehtukas / harrier',
				67950 => 'veratas / sinister',
				46838 => 'Carrion	Occam',
				46952 => 'Rabid	Grizzlemouth',
				47066 => 'Dire	Mathilde',
				72314 => 'tizlaks / commander',
				73514 => 'Marauder	Svaard',
				73996 => 'Vigilant	Laranthir',
				75009 => 'Crusader	Ossa',
				75307 => 'Wanderer	Ruka',
				85019 => 'thetwins / grieving',
				71007 => 'yassiths / viper',
				85222 => 'nadijehs / marshal',
				80226 => 'thackerays /seraph',
				76055 => 'Trailblazer	Pahua',
				76501 => 'maklains / minstrel',
				87604 => 'Plaguedoctor	Nerashi',
				47028 => 'theodosuss / cleric',
				46971 => 'hronks / magi',
				86594 => 'tixxs /giver',
				46895 => 'Apothecary	Ebonmane',
				47009 => 'Celestial	Wupwup',
				89706 => 'steelstars / diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1b8fd49c1',
			'label' => 'swords',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas / berserker',
				46831 => 'beigarthsblade sword knight',
				46983 => 'hronksblade sword magi',
				47040 => 'theodosussblade sword cleric',
				47059 => 'sorossblade sword assassin',
				49879 => 'keepersblade sword zealot',
				66672 => 'ventarisblade sword nomad',
				67938 => 'veratasblade sword sinister',
				70838 => 'yassithsblade sword viper',
				73724 => 'tizlaksblade	sword commander',
				76730 => 'maklainsblade sword minstrel',
				84876 => 'thetwinsblade sword grieving',
				84939 => 'zehtukasblade sword harrier',
				85008 => 'nadijehsblade sword marshal',
				86662 => 'tixxsblade sword giver',
				89645 => 'steelstarsblade sword diviner',
				46812 => 'Valkyrie Stonecleaver',
				47002 => 'Soldier Chorben',
				46793 => 'Rampager Coalforge',
				46945 => 'Cavalier Angchu',
				46926 => 'Settler	Leftpaw',
				46888 => 'Sentinel Tonn',
				46869 => 'Shaman Zintl',
				46850 => 'Carrion Occam',
				46964 => 'Rabid Grizzlemouth',
				47078 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				74064 => 'Vigilant Laranthir',
				73373 => 'Crusader Ossa',
				72079 => 'Wanderer Ruka',
				73984 => 'Trailblazer Pahua',
				87885 => 'Plaguedoctor Nerashi',
				46907 => 'Apothecary Ebonmane',
				47021 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c1eb01cf58',
			'label' => 'Maces',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'mace',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46766 => 'zojjasflangedmace	mace	berserker',
				46823 => 'beigarthsflangedmace	mace	knight',
				46975 => 'hronksflangedmace	mace	magi',
				47032 => 'theodosussflangedmace	mace	cleric',
				47051 => 'sorossflangedmace	mace	assassin',
				49888 => 'keepersflangedmace	mace	zealot',
				66681 => 'ventarisflangedmace	mace	nomad',
				67946 => 'veratasflangedmace	mace	sinister',
				71457 => 'maklainsflangedmace	mace	minstrel',
				76786 => 'yassithsflangedmace	mace	viper',
				76988 => 'tizlaksflangedmace	mace	commander',
				80624 => 'thackeraysgavel	mace	seraph',
				84912 => 'zehtukasflangedmace	mace	harrier',
				85166 => 'nadijehsflangedmace	mace	marshal',
				85295 => 'thetwinsflangedmace	mace	grieving',
				86504 => 'tixxsflangedmace	mace	giver',
				89707 => 'steelstars diviner',
				46804 => 'Valkyrie Stonecleaver',
				46994 => 'Soldier Chorben',
				46785 => 'Rampager Coalforge',
				46937 => 'Cavalier Angchu',
				46918 => 'Settlers Leftpaw',
				46880 => 'Sentinel Tonn',
				'46861": Shaman Zintl' => '46861": Shaman Zintl',
				46842 => 'Carrion Occam',
				46956 => 'Rabid Grizzlemouth',
				47070 => 'Dire Mathilde',
				75559 => 'Marauder Svaard',
				73631 => 'Vigilant Laranthir',
				75581 => 'Crusader Ossa',
				73487 => 'Wanderer Ruka",',
				71472 => 'Trailblazer Pahua',
				87739 => 'Plaguedoctors Nerashi',
				46899 => 'Apothecary Ebonmane',
				47013 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c209b996f4',
			'label' => 'scepters',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'scepter',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46769 => 'zojjaswand	scepter	berserker',
				46826 => 'beigarthswand	scepter	knight',
				46978 => 'hronkswand	scepter	magi',
				47035 => 'theodosusswand	scepter	cleric',
				47054 => 'sorosswand	scepter	assassin',
				49891 => 'keeperswand	scepter	zealot',
				66674 => 'ventariswand	scepter	nomad',
				67943 => 'verataswand	scepter	sinister',
				73220 => 'maklainswand	scepter	minstrel',
				76688 => 'yassithswand	scepter	viper',
				76821 => 'tizlaks commander',
				85027 => 'zehtukas harrier',
				85076 => 'thetwins grieving',
				85109 => 'nadijehs marshal',
				86443 => 'tixxs giver',
				89484 => 'steelstars diviner',
				46807 => 'Valkyrie Stonecleaver',
				46997 => 'Soldier Chorben',
				46788 => 'Rampager Coalforge',
				46940 => 'Cavalier	Angchu',
				46921 => 'Settler	Leftpaw',
				46883 => 'Sentinel	Tonn',
				46864 => 'Shaman	Zintl',
				46845 => 'Carrion	Occam',
				46959 => 'Rabid	Grizzlemouth',
				'47073 ; Dire	Mathilde' => '47073 ; Dire	Mathilde',
				75269 => 'Marauder	Svaard',
				74056 => 'Vigilant	Laranthir',
				74124 => 'Crusader	Ossa',
				76049 => 'Wanderer	Ruka',
				73287 => 'Trailblazer	Pahua',
				'87857 ; Plaguedoctor	Nerashi' => '87857 ; Plaguedoctor	Nerashi',
				46902 => 'Apothecary	Ebonmane',
				47016 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c21d38041a',
			'label' => 'Staffs',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'staff',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46773 => 'zojjasspire	staff	berserker',
				46830 => 'beigarthsspire	staff	knight',
				46982 => 'hronksspire	staff	magi',
				47039 => 'theodosussspire	staff	cleric',
				47058 => 'sorossspire	staff	assassin',
				49878 => 'keepersspire	staff	zealot',
				66680 => 'ventarisspire	staff	nomad',
				67939 => 'veratasspire	staff	sinister',
				71387 => 'yassithsspire	staff	viper',
				75200 => 'maklainsspire	staff	minstrel',
				76089 => 'tizlaksspire	staff	commander',
				85001 => 'thetwinsspire	staff	grieving',
				85112 => 'zehtukasspire	staff	harrier',
				85356 => 'nadijehsspire	staff	marshal',
				86561 => 'tixxsspire	staff	giver',
				89945 => 'steelstarsspire	staff	diviner',
				46811 => 'Valkyrie Stonecleaver',
				47001 => 'Soldier Chorben',
				46792 => 'Rampager Coalforge',
				46944 => 'Cavalier Angchu',
				46925 => 'Settler Leftpaw',
				46887 => 'Sentinel Tonn',
				46868 => 'Shaman Zintl',
				46849 => 'Carrion Occam',
				46963 => 'Rabid Grizzlemouth',
				47077 => 'Dire Mathilde',
				76889 => 'Marauder Svaard',
				76631 => 'Vigilant Laranthir',
				70416 => 'Crusader Ossa',
				74735 => 'Wanderer Ruka',
				72927 => 'Trailblazer Pahua',
				87785 => 'Plaguedoctor Nerashi',
				46906 => 'Apothecary Ebonmane',
				47020 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c23209f368',
			'label' => 'daggers',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c25928b116',
			'label' => 'Pistol',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol diviner',
				46805 => 'Valkyrie Stonecleaver',
				46995 => 'Soldier Chorben',
				46786 => 'Rampager Coalforge',
				46938 => 'Cavalier Angchu',
				46919 => 'Settler	Leftpaw',
				46881 => 'Sentinel Tonn',
				46862 => 'Shaman Zintl',
				46843 => 'Carrion Occam',
				46957 => 'Rabid Grizzlemouth',
				47071 => 'Dire Mathilde',
				70482 => 'Marauder Svaard',
				74612 => 'Vigilant Laranthir',
				73925 => 'Crusader Ossa',
				72108 => 'Wanderer Ruka',
				72860 => 'Trailblazer Pahua',
				88047 => 'Plaguedoctor Nerashi',
				46900 => 'Apothecary Ebonmane',
				47014 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c87d90469375',
			'label' => 'Pistol (oh1)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol diviner',
				46805 => 'Valkyrie Stonecleaver',
				46995 => 'Soldier Chorben',
				46786 => 'Rampager Coalforge',
				46938 => 'Cavalier Angchu',
				46919 => 'Settler	Leftpaw',
				46881 => 'Sentinel Tonn',
				46862 => 'Shaman Zintl',
				46843 => 'Carrion Occam',
				46957 => 'Rabid Grizzlemouth',
				47071 => 'Dire Mathilde',
				70482 => 'Marauder Svaard',
				74612 => 'Vigilant Laranthir',
				73925 => 'Crusader Ossa',
				72108 => 'Wanderer Ruka',
				72860 => 'Trailblazer Pahua',
				88047 => 'Plaguedoctor Nerashi',
				46900 => 'Apothecary Ebonmane',
				47014 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c87d641a7543',
			'label' => 'Pistol (offhand2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol diviner',
				46805 => 'Valkyrie Stonecleaver',
				46995 => 'Soldier Chorben',
				46786 => 'Rampager Coalforge',
				46938 => 'Cavalier Angchu',
				46919 => 'Settler	Leftpaw',
				46881 => 'Sentinel Tonn',
				46862 => 'Shaman Zintl',
				46843 => 'Carrion Occam',
				46957 => 'Rabid Grizzlemouth',
				47071 => 'Dire Mathilde',
				70482 => 'Marauder Svaard',
				74612 => 'Vigilant Laranthir',
				73925 => 'Crusader Ossa',
				72108 => 'Wanderer Ruka',
				72860 => 'Trailblazer Pahua',
				88047 => 'Plaguedoctor Nerashi',
				46900 => 'Apothecary Ebonmane',
				47014 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c87d62ba7542',
			'label' => 'Pistol (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'pistol',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46767 => 'zojjasrevolver	pistol	berserker',
				46824 => 'beigarthsrevolver	pistol	knight',
				46976 => 'hronksrevolver	pistol	magi',
				47033 => 'theodosussrevolver	pistol	cleric',
				47052 => 'sorossrevolver	pistol	assassin',
				49889 => 'keepersrevolver	pistol	zealot',
				66689 => 'ventarisrevolver	pistol	nomad',
				67945 => 'veratasrevolver	pistol	sinister',
				72239 => 'yassithsrevolver	pistol	viper',
				73549 => 'maklainsrevolver	pistol	minstrel',
				73614 => 'tizlaksrevolver	pistol	commander',
				84878 => 'zehtukasrevolver	pistol	harrier',
				84931 => 'thetwinsrevolver	pistol	grieving',
				85061 => 'nadijehsrevolver	pistol	marshal',
				86300 => 'marshalsstellarrevolver	pistol	marshal',
				86526 => 'tixxsrevolver	pistol	giver',
				89716 => 'steelstarsrevolver	pistol diviner',
				46805 => 'Valkyrie Stonecleaver',
				46995 => 'Soldier Chorben',
				46786 => 'Rampager Coalforge',
				46938 => 'Cavalier Angchu',
				46919 => 'Settler	Leftpaw',
				46881 => 'Sentinel Tonn',
				46862 => 'Shaman Zintl',
				46843 => 'Carrion Occam',
				46957 => 'Rabid Grizzlemouth',
				47071 => 'Dire Mathilde',
				70482 => 'Marauder Svaard',
				74612 => 'Vigilant Laranthir',
				73925 => 'Crusader Ossa',
				72108 => 'Wanderer Ruka',
				72860 => 'Trailblazer Pahua',
				88047 => 'Plaguedoctor Nerashi',
				46900 => 'Apothecary Ebonmane',
				47014 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c263265550',
			'label' => 'Rifle',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'rifle',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46768 => 'zojjasmusket	rifle	berserker',
				46825 => 'beigarthsmusket	rifle	knight',
				46977 => 'hronksmusket	rifle	magi',
				47034 => 'theodosussmusket	rifle	cleric',
				47053 => 'sorossmusket	rifle	assassin',
				49890 => 'keepersmusket	rifle	zealot',
				66679 => 'ventarismusket	rifle	nomad',
				67952 => 'veratasmusket	rifle	sinister',
				71219 => 'tizlaksmusket	rifle	commander',
				72279 => 'yassithsmusket	rifle	viper',
				73497 => 'maklainsmusket	rifle	minstrel',
				84886 => 'nadijehsmusket	rifle	marshal',
				85072 => 'thetwinsmusket	rifle	grieving',
				85348 => 'zehtukasmusket	rifle	harrier',
				89736 => 'steelstarsmusket	rifle	diviner',
				46806 => 'Valkyrie Stonecleaver',
				46996 => 'Soldier Chorben',
				46787 => 'Rampager Coalforge',
				46939 => 'Cavalier Angchu',
				46920 => 'Settler Leftpaw',
				46882 => 'Sentinel Tonn',
				46863 => 'Shaman Zintl',
				46844 => 'Carrion Occam',
				46958 => 'Rabid Grizzlemouth',
				47072 => 'Dire Mathilde',
				71478 => 'Marauder Svaard',
				73357 => 'Vigilant Laranthir',
				70729 => 'Crusader Ossa',
				77055 => 'Wanderer Ruka',
				76984 => 'Trailblazer Pahua',
				87956 => 'Plaguedoctor Nerashi',
				46901 => 'Apothecary Ebonmane',
				47015 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2730a4eda',
			'label' => 'Shortbow',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'shortbow',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46771 => 'zojjas berserker',
				46828 => 'beigarths knight',
				46980 => 'hronks magi',
				47037 => 'theodosuss cleric',
				47056 => 'soross assassin',
				49876 => 'keepers zealot',
				66676 => 'ventaris nomad',
				67941 => 'veratas sinister',
				74083 => 'tizlaks commander',
				74569 => 'yassiths viper',
				75644 => 'maklains minstrel',
				80391 => 'thackerays seraph',
				85156 => 'nadijehs marshal',
				85200 => 'zehtukas harrier',
				85242 => 'thetwins grieving',
				86706 => 'tixxs giver',
				89949 => 'steelstars diviner',
				46809 => 'Valkyrie Stonecleaver',
				46999 => 'Soldier Chorben',
				46790 => 'Rampager	Coalforge',
				46942 => 'Cavalier Angchu',
				46923 => 'Settler Leftpaw',
				46885 => 'Sentinel Tonn',
				46866 => 'Shaman Zintl',
				46847 => 'Carrion Occam',
				46961 => 'Rabid Grizzlemouth',
				47075 => 'Dire Mathilde',
				73280 => 'Marauder Svaard',
				76878 => 'Vigilant Laranthir',
				71645 => 'Crusader Ossa',
				75743 => 'Wanderer Ruka',
				76256 => 'Trailblazer Pahua',
				87811 => 'Plaguedoctor Nerashi',
				46904 => 'Apothecary Ebonmane',
				47018 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c287570535',
			'label' => 'longbow',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'longbow',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46765 => 'zojjas berserker',
				46822 => 'beigarths knight',
				46974 => 'hronksgreatbow	longbow	magi',
				47031 => 'theodosussgreatbow	longbow	cleric',
				47050 => 'sorossgreatbow	longbow	assassin',
				49887 => 'keepersgreatbow	longbow	zealot',
				66682 => 'ventarisgreatbow	longbow	nomad',
				67947 => 'veratasgreatbow	longbow	sinister',
				70504 => 'yassithsgreatbow	longbow	viper',
				73948 => 'maklainsgreatbow	longbow	minstrel',
				74953 => 'tizlaksgreatbow	longbow	commander',
				80402 => 'thackeraysgreatbow	longbow	seraph',
				85073 => 'nadijehsgreatbow	longbow	marshal',
				85111 => 'zehtukasgreatbow	longbow	harrier',
				85212 => 'thetwinsgreatbow	longbow	grieving',
				86483 => 'tixxsgreatbow	longbow	giver',
				89681 => 'steelstarsgreatbow	longbow	diviner',
				46803 => 'Valkyrie Stonecleaver',
				46993 => 'Soldier Chorben',
				46784 => 'Rampager Coalforge',
				46936 => 'Cavalier Angchu',
				46917 => 'Settler Leftpaw',
				46879 => 'Sentinel Tonn',
				46860 => 'Shaman Zintl',
				46841 => 'Carrion Occam',
				46955 => 'Rabid Grizzlemouth',
				47069 => 'Dire Mathilde',
				75747 => 'Marauder Svaard',
				75025 => 'Vigilant Laranthir',
				74935 => 'Crusader Ossa',
				71114 => 'Wanderer Ruka',
				75642 => 'Trailblazer Pahua',
				87866 => 'Plaguedoctor Nerashi',
				46898 => 'Apothecary Ebonmane',
				47012 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c28d3b54bc',
			'label' => 'axe',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'axe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46759 => 'zojjas berserker',
				46816 => 'beigarths knight',
				46968 => 'hronks magi',
				47025 => 'theodosuss cleric',
				47044 => 'soross assassin',
				49880 => 'keepers zealot',
				66673 => 'ventaris nomad',
				67944 => 'veratas sinister',
				72476 => 'tizlaks commander',
				74905 => 'maklains minstrel',
				77122 => 'yassiths viper',
				85047 => 'zehtuka harrier',
				85233 => 'nadijehs marshal',
				85253 => 'thetwins grieving',
				86444 => 'tixxs giver',
				89799 => 'steelstars diviner',
				46797 => 'Valkyrie Stonecleaver',
				46987 => 'Soldier Chorben',
				46778 => 'Rampager Coalforge',
				46930 => 'Cavalier Angchu',
				46911 => 'Settler Leftpaw',
				46873 => 'Sentinel Tonn',
				46854 => 'Shaman Zintl',
				46835 => 'Carrion Occam',
				46949 => 'Rabid Grizzlemouth',
				47063 => 'Dire Mathilde',
				72882 => 'Marauder Svaard',
				75224 => 'Vigilant Laranthir',
				75667 => 'Crusader Ossa',
				74679 => 'Wanderer Ruka',
				71361 => 'Trailblazer Pahua',
				87605 => 'Plaguedoctor Nerashi',
				46892 => 'Apothecary Ebonmane',
				47006 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d547fdc85e',
			'label' => 'hammer',
			'name' => 'mh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6c152fd49bf',
						'operator' => '==',
						'value' => 'hammer',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46763 => 'zojjas berserker',
				46820 => 'beigarths knight',
				46972 => 'hronks magi',
				47029 => 'theodosuss cleric',
				47048 => 'soross assassin',
				49885 => 'keepers zealot',
				66684 => 'ventaris nomad',
				67949 => 'veratas sinister',
				74363 => 'yassiths viper',
				76262 => 'maklains minstrel',
				76977 => 'tizlaks commander',
				80522 => 'thackerays seraph',
				85228 => 'zehtukas harrier',
				85249 => 'thetwins grieving',
				85347 => 'nadijehs marshal',
				86564 => 'tixxs giver',
				89773 => 'steelstars diviner',
				46801 => 'Valkyrie Stonecleaver',
				46991 => 'Soldier Chorben',
				46782 => 'Rampager Coalforge',
				46934 => 'Cavalier Angchu',
				46915 => 'Settler	Leftpaw',
				46877 => 'Sentinel Tonn',
				46858 => 'Shaman Zintl',
				46839 => 'Carrion Occam',
				46953 => 'Rabid Grizzlemouth',
				47067 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				75174 => 'Vigilant Laranthir',
				'73298: Crusader Ossa' => '73298: Crusader Ossa',
				75521 => 'Wanderer Ruka',
				74776 => 'Trailblazer Pahua',
				'87671: Plaguedoctor Nerashi' => '87671: Plaguedoctor Nerashi',
				'46896: Apothecary Ebonmane' => '46896: Apothecary Ebonmane',
				47010 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4286b76e2',
			'label' => 'offhand1',
			'name' => 'offhand1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				'warhorn :Warhorn' => 'warhorn :Warhorn',
				'Dagger' => 'dagger',
				'axe' => 'axe',
				'shield' => 'shield',
				'torch :Torch' => 'torch :Torch',
				'sword' => 'sword',
				'pistol' => 'pistol',
				'focus' => 'focus',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4455b76e6',
			'label' => 'swords (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				46774 => 'zojjas / berserker',
				46831 => 'beigarthsblade	sword	knight',
				'46983 :	hronksblade	sword	magi' => '46983 :	hronksblade	sword	magi',
				'47040 :	theodosussblade	sword	cleric' => '47040 :	theodosussblade	sword	cleric',
				'47059 :	sorossblade	sword	assassin' => '47059 :	sorossblade	sword	assassin',
				'49879 :	keepersblade	sword	zealot' => '49879 :	keepersblade	sword	zealot',
				'66672 :	ventarisblade	sword	nomad' => '66672 :	ventarisblade	sword	nomad',
				'67938 :	veratasblade	sword	sinister' => '67938 :	veratasblade	sword	sinister',
				'70838 :	yassithsblade	sword	viper' => '70838 :	yassithsblade	sword	viper',
				'73724 :	tizlaksblade	sword	commander' => '73724 :	tizlaksblade	sword	commander',
				'76730 :	maklainsblade	sword	minstrel' => '76730 :	maklainsblade	sword	minstrel',
				'84876 :	thetwinsblade	sword	grieving' => '84876 :	thetwinsblade	sword	grieving',
				'84939 :	zehtukasblade	sword	harrier' => '84939 :	zehtukasblade	sword	harrier',
				'85008 :	nadijehsblade	sword	marshal' => '85008 :	nadijehsblade	sword	marshal',
				'86662 :	tixxsblade	sword	giver' => '86662 :	tixxsblade	sword	giver',
				'89645 :	steelstarsblade	sword	diviner' => '89645 :	steelstarsblade	sword	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d4417b76e4',
			'label' => 'axe (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'axe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				46759 => 'zojjas berserker',
				46816 => 'beigarths knight',
				46968 => 'hronks magi',
				47025 => 'theodosuss cleric',
				47044 => 'soross assassin',
				49880 => 'keepers zealot',
				66673 => 'ventaris nomad',
				67944 => 'veratas sinister',
				72476 => 'tizlaks commander',
				74905 => 'maklains minstrel',
				77122 => 'yassiths viper',
				85047 => 'zehtuka harrier',
				85233 => 'nadijehs marshal',
				85253 => 'thetwins grieving',
				86444 => 'tixxs giver',
				89799 => 'steelstars diviner',
				46797 => 'Valkyrie Stonecleaver',
				46987 => 'Soldier Chorben',
				46778 => 'Rampager Coalforge',
				46930 => 'Cavalier Angchu',
				46911 => 'Settler Leftpaw',
				46873 => 'Sentinel Tonn',
				46854 => 'Shaman Zintl',
				46835 => 'Carrion Occam',
				46949 => 'Rabid Grizzlemouth',
				47063 => 'Dire Mathilde',
				72882 => 'Marauder Svaard',
				75224 => 'Vigilant Laranthir',
				75667 => 'Crusader Ossa',
				74679 => 'Wanderer Ruka',
				71361 => 'Trailblazer Pahua',
				87605 => 'Plaguedoctor Nerashi',
				46892 => 'Apothecary Ebonmane',
				47006 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c87d566a7541',
			'label' => 'axe (offhand2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'axe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				46759 => 'zojjas berserker',
				46816 => 'beigarths knight',
				46968 => 'hronks magi',
				47025 => 'theodosuss cleric',
				47044 => 'soross assassin',
				49880 => 'keepers zealot',
				66673 => 'ventaris nomad',
				67944 => 'veratas sinister',
				72476 => 'tizlaks commander',
				74905 => 'maklains minstrel',
				77122 => 'yassiths viper',
				85047 => 'zehtuka harrier',
				85233 => 'nadijehs marshal',
				85253 => 'thetwins grieving',
				86444 => 'tixxs giver',
				89799 => 'steelstars diviner',
				46797 => 'Valkyrie Stonecleaver',
				46987 => 'Soldier Chorben',
				46778 => 'Rampager Coalforge',
				46930 => 'Cavalier Angchu',
				46911 => 'Settler Leftpaw',
				46873 => 'Sentinel Tonn',
				46854 => 'Shaman Zintl',
				46835 => 'Carrion Occam',
				46949 => 'Rabid Grizzlemouth',
				47063 => 'Dire Mathilde',
				72882 => 'Marauder Svaard',
				75224 => 'Vigilant Laranthir',
				75667 => 'Crusader Ossa',
				74679 => 'Wanderer Ruka',
				71361 => 'Trailblazer Pahua',
				87605 => 'Plaguedoctor Nerashi',
				46892 => 'Apothecary Ebonmane',
				47006 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d43f3b76e3',
			'label' => 'daggers (offhand)',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'Dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				46760 => 'zojjasrazor	dagger	berserker',
				46817 => 'beigarthsrazor	dagger	knight',
				46969 => 'hronksrazor	dagger	magi',
				47026 => 'theodosussrazor	dagger	cleric',
				47045 => 'sorossrazor	dagger	assassin',
				49882 => 'keepersrazor	dagger	zealot',
				66687 => 'ventarisrazor	dagger	nomad',
				67948 => 'veratasrazor	dagger	sinister',
				73059 => 'tizlaksrazor	dagger	commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehsrazor	dagger	marshal',
				84936 => 'thetwinsrazor	dagger	grieving',
				85051 => 'zehtukasrazor	dagger	harrier',
				86085 => 'marshalsstellarrazor	dagger	marshal',
				86689 => 'tixxsrazor	dagger	giver',
				89906 => 'steelstarsrazor	dagger	diviner',
				'Valkyrie	Stonecleaver' => 'Valkyrie	Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				'Sentinel	Tonn' => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				'Apothecary	Ebonmane' => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c292e714df',
			'label' => 'focus',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'focus',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46761 => 'zojjas berserker',
				46818 => 'beigarthsartifact	focus	knight',
				46970 => 'hronksartifact	focus	magi',
				'47027 ; theodosussartifact	focus	cleric' => '47027 ; theodosussartifact	focus	cleric',
				47046 => 'sorossartifact	focus	assassin',
				49874 => 'keepersartifact	focus	zealot',
				66686 => 'ventarisartifact	focus	nomad',
				67951 => 'veratasartifact	focus	sinister',
				71584 => 'yassithsartifact	focus	viper',
				72188 => 'maklainsartifact	focus	minstrel',
				75356 => 'tizlaksartifact	focus	commander',
				85044 => 'thetwinsartifact	focus	grieving',
				85224 => 'nadijehsartifact	focus	marshal',
				85346 => 'zehtukasartifact	focus	harrier',
				86463 => 'tixxsartifact	focus	giver',
				89846 => 'steelstarsartifact	focus	diviner',
				46799 => 'Valkyrie Stonecleaver',
				46989 => 'Soldier Chorben',
				46780 => 'Rampager Coalforge',
				46932 => 'Cavalier Angchu',
				46913 => 'Settler Leftpaw',
				46875 => 'Sentinel Tonn',
				46856 => 'Shaman Zintl',
				46837 => 'Carrion Occam',
				46951 => 'Rabid Grizzlemouth',
				47065 => 'Dire Mathilde',
				74516 => 'Marauder Svaard',
				75668 => 'Vigilant Laranthir',
				72005 => 'Crusader	Ossa',
				73068 => 'Wanderer	Ruka',
				75331 => 'Trailblazer	Pahua',
				87592 => 'Plaguedoctor	Nerashi',
				46894 => 'Apothecary	Ebonmane',
				47008 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c92d1a8b5f01',
			'label' => 'focus (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => '',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46761 => 'zojjas berserker',
				46818 => 'beigarthsartifact	focus	knight',
				46970 => 'hronksartifact	focus	magi',
				'47027 ; theodosussartifact	focus	cleric' => '47027 ; theodosussartifact	focus	cleric',
				47046 => 'sorossartifact	focus	assassin',
				49874 => 'keepersartifact	focus	zealot',
				66686 => 'ventarisartifact	focus	nomad',
				67951 => 'veratasartifact	focus	sinister',
				71584 => 'yassithsartifact	focus	viper',
				72188 => 'maklainsartifact	focus	minstrel',
				75356 => 'tizlaksartifact	focus	commander',
				85044 => 'thetwinsartifact	focus	grieving',
				85224 => 'nadijehsartifact	focus	marshal',
				85346 => 'zehtukasartifact	focus	harrier',
				86463 => 'tixxsartifact	focus	giver',
				89846 => 'steelstarsartifact	focus	diviner',
				46799 => 'Valkyrie Stonecleaver',
				46989 => 'Soldier Chorben',
				46780 => 'Rampager Coalforge',
				46932 => 'Cavalier Angchu',
				46913 => 'Settler Leftpaw',
				46875 => 'Sentinel Tonn',
				46856 => 'Shaman Zintl',
				46837 => 'Carrion Occam',
				46951 => 'Rabid Grizzlemouth',
				47065 => 'Dire Mathilde',
				74516 => 'Marauder Svaard',
				75668 => 'Vigilant Laranthir',
				72005 => 'Crusader	Ossa',
				73068 => 'Wanderer	Ruka',
				75331 => 'Trailblazer	Pahua',
				'87592 Plaguedoctor	Nerashi' => '87592 Plaguedoctor	Nerashi',
				46894 => 'Apothecary	Ebonmane',
				47008 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2963c1bfc',
			'label' => 'shield',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'shield',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46770 => 'zojjasbastion	shield	berserker',
				46827 => 'beigarthsbastion	shield	knight',
				46979 => 'hronksbastion	shield	magi',
				47036 => 'theodosussbastion	shield	cleric',
				47055 => 'sorossbastion	shield	assassin',
				49875 => 'keepersbastion	shield	zealot',
				66675 => 'ventarisbastion	shield	nomad',
				67942 => 'veratasbastion	shield	sinister',
				71944 => 'yassithsbastion	shield	viper',
				74748 => 'maklainsbastion	shield	minstrel',
				76075 => 'tizlaksbastion	shield	commander',
				84957 => 'zehtukasbastion	shield	harrier',
				85266 => 'thetwinsbastion	shield	grieving',
				85357 => 'nadijehsbastion	shield	marshal',
				86505 => 'tixxsbastion	shield	giver',
				89922 => 'steelstarsbastion	shield	diviner',
				'Valkyrie Stonecleaver' => 'Valkyrie Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				46884 => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				46903 => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c8bb6acbfae5',
			'label' => 'shield (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'shield',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46770 => 'zojjasbastion	shield	berserker',
				46827 => 'beigarthsbastion	shield	knight',
				46979 => 'hronksbastion	shield	magi',
				47036 => 'theodosussbastion	shield	cleric',
				47055 => 'sorossbastion	shield	assassin',
				49875 => 'keepersbastion	shield	zealot',
				66675 => 'ventarisbastion	shield	nomad',
				67942 => 'veratasbastion	shield	sinister',
				71944 => 'yassithsbastion	shield	viper',
				74748 => 'maklainsbastion	shield	minstrel',
				76075 => 'tizlaksbastion	shield	commander',
				84957 => 'zehtukasbastion	shield	harrier',
				85266 => 'thetwinsbastion	shield	grieving',
				85357 => 'nadijehsbastion	shield	marshal',
				86505 => 'tixxsbastion	shield	giver',
				89922 => 'steelstarsbastion	shield	diviner',
				'Valkyrie Stonecleaver' => 'Valkyrie Stonecleaver',
				'Soldier	Chorben' => 'Soldier	Chorben',
				'Rampager	Coalforge' => 'Rampager	Coalforge',
				'Cavalier	Angchu' => 'Cavalier	Angchu',
				'Settler	Leftpaw' => 'Settler	Leftpaw',
				46884 => 'Sentinel	Tonn',
				'Shaman	Zintl' => 'Shaman	Zintl',
				'Carrion	Occam' => 'Carrion	Occam',
				'Rabid	Grizzlemouth' => 'Rabid	Grizzlemouth',
				'Dire	Mathilde' => 'Dire	Mathilde',
				'Marauder	Svaard' => 'Marauder	Svaard',
				'Vigilant	Laranthir' => 'Vigilant	Laranthir',
				'Crusader	Ossa' => 'Crusader	Ossa',
				'Wanderer	Ruka' => 'Wanderer	Ruka',
				'Trailblazer	Pahua' => 'Trailblazer	Pahua',
				'Plaguedoctor	Nerashi' => 'Plaguedoctor	Nerashi',
				46903 => 'Apothecary	Ebonmane',
				'Celestial	Wupwup' => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6c2a1ffcc17',
			'label' => 'warhorn',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46777 => 'zojjasherald	warhorn	berserker',
				46834 => 'beigarthsherald	warhorn	knight',
				46986 => 'hronksherald	warhorn	magi',
				47043 => 'theodosussherald	warhorn	cleric',
				47062 => 'sorossherald	warhorn	assassin',
				49883 => 'keepersherald	warhorn	zealot',
				66678 => 'ventarisherald	warhorn	nomad',
				67936 => 'veratasherald	warhorn	sinister',
				71116 => 'maklainsherald	warhorn	minstrel',
				71117 => 'tizlaksherald	warhorn	commander',
				75325 => 'yassithsherald	warhorn	viper',
				84973 => 'zehtukasherald	warhorn	harrier',
				85074 => 'thetwinsherald	warhorn	grieving',
				85116 => 'nadijehs marshal',
				86440 => 'tixxsherald giver',
				89624 => 'steelstars diviner',
				46815 => 'Valkyrie Stonecleaver',
				47005 => 'Soldier Chorben',
				46796 => 'Rampager Coalforge',
				46948 => 'Cavalier Angchu',
				46929 => 'Settler Leftpaw',
				46891 => 'Sentinel Tonn',
				46872 => 'Shaman Zintl',
				46853 => 'Carrion Occam',
				46967 => 'Rabid Grizzlemouth',
				47081 => 'Dire Mathilde',
				75201 => 'Marauder Svaard',
				76824 => 'Vigilant Laranthir',
				71005 => 'Crusader Ossa',
				75042 => 'Wanderer Ruka',
				75697 => 'Trailblazer Pahua',
				87898 => 'Plaguedoctor Nerashi',
				46910 => 'Apothecary Ebonmane',
				47024 => 'Celestial Wupwup',
				80407 => 'thackeray seraph',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6d70ae45462',
			'label' => 'Torch',
			'name' => 'oh1',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46775 => 'zojjas berserker',
				'46832: beigarths knight' => '46832: beigarths knight',
				46984 => 'hronks magi',
				47041 => 'theodosuss cleric',
				47060 => 'soross assassin',
				49881 => 'keepers zealot',
				66688 => 'ventaris nomad',
				67937 => 'veratas sinister',
				76271 => 'yassiths viper',
				'75820 maklains minstrel' => '75820 maklains minstrel',
				'75611 tizlaks commander' => '75611 tizlaks commander',
				80683 => 'thackerays seraph',
				85013 => 'zehtukas harrier',
				85006 => 'thetwins grieving',
				85152 => 'nadijehs marshal',
				86439 => 'Tixxs giver',
				89612 => 'steelstars diviner',
				46813 => 'Valkyrie Stonecleaver',
				47003 => 'Soldier Chorben',
				46794 => 'Rampager Coalforge',
				46946 => 'Cavalier Angchu',
				46927 => 'Settler Leftpaw',
				46889 => 'Sentinel Tonn',
				46870 => 'Shaman Zintl',
				46851 => 'Carrion Occam',
				46965 => 'Rabid Grizzlemouth',
				47079 => 'Dire Mathilde',
				74500 => 'Marauder Svaard',
				71161 => 'Vigilant Laranthir',
				72004 => 'Crusader Ossa',
				72893 => 'Wanderer Ruka',
				72256 => 'Trailblazer Pahua',
				'87858: Plaguedoctor Nerashi' => '87858: Plaguedoctor Nerashi',
				46908 => 'Apothecary Ebonmane',
				47022 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de54f534e1',
			'label' => 'mainweap2',
			'name' => 'mainweap2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty (ele/engy)' => ': empty (ele/engy)',
				'greatsword' => 'Greatsword',
				'sword' => 'Sword',
				'hammer' => 'hammer',
				'mace' => 'Mace',
				'scepter' => 'Scepter',
				'staff' => 'Staff',
				'dagger' => 'Dagger',
				'pistol' => 'Pistol',
				'rifle' => 'Rifle',
				'shortbow' => 'Shortbow',
				'longbow' => 'Longbow',
				'axe' => 'Axe',
				'focus' => 'Focus',
				'shield' => 'Shield',
				'warhorn' => 'Warhorn',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ca896798d4ba',
			'label' => 'hammer (hm2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'hammer',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46763 => 'zojjas berserker',
				46820 => 'beigarths knight',
				46972 => 'hronks magi',
				47029 => 'theodosuss cleric',
				47048 => 'soross assassin',
				49885 => 'keepers zealot',
				66684 => 'ventaris nomad',
				67949 => 'veratas sinister',
				74363 => 'yassiths viper',
				76262 => 'maklains minstrel',
				76977 => 'tizlaks commander',
				80522 => 'thackerays seraph',
				85228 => 'zehtukas harrier',
				85249 => 'thetwins grieving',
				85347 => 'nadijehs marshal',
				86564 => 'tixxs giver',
				89773 => 'steelstars diviner',
				46801 => 'Valkyrie Stonecleaver',
				46991 => 'Soldier Chorben',
				46782 => 'Rampager Coalforge',
				46934 => 'Cavalier Angchu',
				46915 => 'Settler	Leftpaw',
				46877 => 'Sentinel Tonn',
				46858 => 'Shaman Zintl',
				46839 => 'Carrion Occam',
				46953 => 'Rabid Grizzlemouth',
				47067 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				75174 => 'Vigilant Laranthir',
				'73298: Crusader Ossa' => '73298: Crusader Ossa',
				75521 => 'Wanderer Ruka',
				74776 => 'Trailblazer Pahua',
				'87671: Plaguedoctor Nerashi' => '87671: Plaguedoctor Nerashi',
				'46896: Apothecary Ebonmane' => '46896: Apothecary Ebonmane',
				47010 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c8d014bbb4be',
			'label' => 'scepters (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'scepter',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46769 => 'zojjaswand	scepter	berserker',
				46826 => 'beigarthswand	scepter	knight',
				46978 => 'hronkswand	scepter	magi',
				47035 => 'theodosusswand	scepter	cleric',
				47054 => 'sorosswand	scepter	assassin',
				49891 => 'keeperswand	scepter	zealot',
				66674 => 'ventariswand	scepter	nomad',
				67943 => 'verataswand	scepter	sinister',
				73220 => 'maklainswand	scepter	minstrel',
				76688 => 'yassithswand	scepter	viper',
				76821 => 'tizlaks commander',
				85027 => 'zehtukas harrier',
				85076 => 'thetwins grieving',
				85109 => 'nadijehs marshal',
				86443 => 'tixxs giver',
				89484 => 'steelstars diviner',
				46807 => 'Valkyrie Stonecleaver',
				46997 => 'Soldier Chorben',
				46788 => 'Rampager Coalforge',
				46940 => 'Cavalier	Angchu',
				46921 => 'Settler	Leftpaw',
				46883 => 'Sentinel	Tonn',
				46864 => 'Shaman	Zintl',
				46845 => 'Carrion	Occam',
				46959 => 'Rabid	Grizzlemouth',
				'47073 ; Dire	Mathilde' => '47073 ; Dire	Mathilde',
				75269 => 'Marauder	Svaard',
				74056 => 'Vigilant	Laranthir',
				74124 => 'Crusader	Ossa',
				76049 => 'Wanderer	Ruka',
				73287 => 'Trailblazer	Pahua',
				'87857 ; Plaguedoctor	Nerashi' => '87857 ; Plaguedoctor	Nerashi',
				46902 => 'Apothecary	Ebonmane',
				47016 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c8bbbd9e6374',
			'label' => 'Maces (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'mace',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46766 => 'zojjasflangedmace	mace	berserker',
				46823 => 'beigarthsflangedmace	mace	knight',
				46975 => 'hronksflangedmace	mace	magi',
				47032 => 'theodosussflangedmace	mace	cleric',
				47051 => 'sorossflangedmace	mace	assassin',
				49888 => 'keepersflangedmace	mace	zealot',
				66681 => 'ventarisflangedmace	mace	nomad',
				67946 => 'veratasflangedmace	mace	sinister',
				71457 => 'maklainsflangedmace	mace	minstrel',
				76786 => 'yassithsflangedmace	mace	viper',
				76988 => 'tizlaksflangedmace	mace	commander',
				80624 => 'thackeraysgavel	mace	seraph',
				84912 => 'zehtukasflangedmace	mace	harrier',
				85166 => 'nadijehsflangedmace	mace	marshal',
				85295 => 'thetwinsflangedmace	mace	grieving',
				86504 => 'tixxsflangedmace	mace	giver',
				89707 => 'steelstars diviner',
				46804 => 'Valkyrie Stonecleaver',
				46994 => 'Soldier Chorben',
				46785 => 'Rampager Coalforge',
				46937 => 'Cavalier Angchu',
				46918 => 'Settlers Leftpaw',
				46880 => 'Sentinel Tonn',
				'46861": Shaman Zintl' => '46861": Shaman Zintl',
				46842 => 'Carrion Occam',
				46956 => 'Rabid Grizzlemouth',
				47070 => 'Dire Mathilde',
				75559 => 'Marauder Svaard',
				73631 => 'Vigilant Laranthir',
				75581 => 'Crusader Ossa',
				73487 => 'Wanderer Ruka',
				71472 => 'Trailblazer Pahua',
				87739 => 'Plaguedoctors Nerashi',
				46899 => 'Apothecary Ebonmane',
				47013 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de836534e2',
			'label' => 'greatsword (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'greatsword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46762 => 'zojjas / berserker',
				49884 => 'keepers / zealot',
				46800 => 'Stonecleavers / Valkyrie',
				46990 => 'Soldier / Chorben',
				46819 => 'beigarths / knight',
				47047 => 'soross / assassin',
				46781 => 'Rampager	Coalforge',
				46933 => 'Cavalier	Angchu',
				66685 => 'ventaris / nomad',
				46914 => 'Settler	Leftpaw',
				46876 => 'Sentinel	Tonn',
				46857 => 'Shaman	Zintl',
				85121 => 'zehtukas / harrier',
				67950 => 'veratas / sinister',
				46838 => 'Carrion	Occam',
				46952 => 'Rabid	Grizzlemouth',
				47066 => 'Dire	Mathilde',
				72314 => 'tizlaks / commander',
				73514 => 'Marauder	Svaard',
				73996 => 'Vigilant	Laranthir',
				75009 => 'Crusader	Ossa',
				75307 => 'Wanderer	Ruka',
				85019 => 'thetwins / grieving',
				71007 => 'yassiths / viper',
				85222 => 'nadijehs / marshal',
				80226 => 'thackerays /seraph',
				76055 => 'Trailblazer	Pahua',
				76501 => 'maklains / minstrel',
				87604 => 'Plaguedoctor / Nerashi',
				47028 => 'theodosuss / cleric',
				46971 => 'hronks / magi',
				86594 => 'tixxs /giver',
				46895 => 'Apothecary	Ebonmane',
				47009 => 'Celestial Wupwup',
				89706 => 'steelstars / diviner',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de857534e3',
			'label' => 'swords (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas berserker',
				46831 => 'beigarths knight',
				46983 => 'hronks magi',
				47040 => 'theodosuss cleric',
				47059 => 'soross assassin',
				49879 => 'keepers zealot',
				66672 => 'ventaris nomad',
				67938 => 'veratas sinister',
				70838 => 'yassiths viper',
				73724 => 'tizlaks commander',
				76730 => 'maklains minstrel',
				84876 => 'thetwins grieving',
				84939 => 'zehtukas harrier',
				85008 => 'nadijehs marshal',
				86662 => 'tixxs giver',
				89645 => 'steelstars diviner',
				46812 => 'Valkyrie Stonecleaver',
				47002 => 'Soldier Chorben',
				46793 => 'Rampager Coalforge',
				46945 => 'Cavalier Angchu',
				46926 => 'Settler	Leftpaw',
				46888 => 'Sentinel Tonn',
				46869 => 'Shaman Zintl',
				46850 => 'Carrion Occam',
				46964 => 'Rabid Grizzlemouth',
				47078 => 'Dire Mathilde',
				75897 => 'Marauder Svaard',
				74064 => 'Vigilant Laranthir',
				73373 => 'Crusader Ossa',
				72079 => 'Wanderer Ruka',
				73984 => 'Trailblazer Pahua',
				87885 => 'Plaguedoctor Nerashi',
				46907 => 'Apothecary Ebonmane',
				47021 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6de9f0534e4',
			'label' => 'daggers (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassithsrazor	dagger	viper',
				75388 => 'maklainsrazor	dagger	minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6ebe9368eb1',
			'label' => 'Staffs (mh2)',
			'name' => 'mh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6de54f534e1',
						'operator' => '==',
						'value' => 'staff',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46773 => 'zojjasspire	staff	berserker',
				46830 => 'beigarthsspire	staff	knight',
				46982 => 'hronksspire	staff	magi',
				47039 => 'theodosussspire	staff	cleric',
				47058 => 'sorossspire	staff	assassin',
				49878 => 'keepersspire	staff	zealot',
				66680 => 'ventarisspire	staff	nomad',
				67939 => 'veratasspire	staff	sinister',
				71387 => 'yassithsspire	staff	viper',
				75200 => 'maklainsspire	staff	minstrel',
				76089 => 'tizlaksspire	staff	commander',
				85001 => 'thetwinsspire	staff	grieving',
				85112 => 'zehtukasspire	staff	harrier',
				85356 => 'nadijehsspire	staff	marshal',
				86561 => 'tixxsspire	staff	giver',
				89945 => 'steelstarsspire	staff	diviner',
				46811 => 'Valkyrie Stonecleaver',
				47001 => 'Soldier Chorben',
				46792 => 'Rampager Coalforge',
				46944 => 'Cavalier Angchu',
				46925 => 'Settler Leftpaw',
				46887 => 'Sentinel Tonn',
				46868 => 'Shaman Zintl',
				46849 => 'Carrion Occam',
				46963 => 'Rabid Grizzlemouth',
				47077 => 'Dire Mathilde',
				76889 => 'Marauder Svaard',
				76631 => 'Vigilant Laranthir',
				70416 => 'Crusader Ossa',
				74735 => 'Wanderer Ruka',
				72927 => 'Trailblazer Pahua',
				87785 => 'Plaguedoctor Nerashi',
				46906 => 'Apothecary Ebonmane',
				47020 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6dea03534e5',
			'label' => 'offhand2',
			'name' => 'offhand2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': empty' => ': empty',
				'warhorn :Warhorn' => 'warhorn :Warhorn',
				'Dagger' => 'dagger',
				'axe' => 'axe',
				'shield' => 'shield',
				'torch :Torch' => 'torch :Torch',
				'sword' => 'sword',
				'pistol' => 'pistol',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6eb0ecd5d0a',
			'label' => 'Torch (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6d4286b76e2',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46775 => 'zojjas berserker',
				'46832: beigarths knight' => '46832: beigarths knight',
				46984 => 'hronks magi',
				47041 => 'theodosuss cleric',
				47060 => 'soross assassin',
				49881 => 'keepers zealot',
				66688 => 'ventaris nomad',
				67937 => 'veratas sinister',
				76271 => 'yassiths viper',
				'75820 maklains minstrel' => '75820 maklains minstrel',
				'75611 tizlaks commander' => '75611 tizlaks commander',
				80683 => 'thackerays seraph',
				85013 => 'zehtukas harrier',
				85006 => 'thetwins grieving',
				85152 => 'nadijehs marshal',
				86439 => 'Tixxs giver',
				89612 => 'steelstars diviner',
				46813 => 'Valkyrie Stonecleaver',
				47003 => 'Soldier Chorben',
				46794 => 'Rampager Coalforge',
				46946 => 'Cavalier Angchu',
				46927 => 'Settler Leftpaw',
				46889 => 'Sentinel Tonn',
				46870 => 'Shaman Zintl',
				46851 => 'Carrion Occam',
				46965 => 'Rabid Grizzlemouth',
				47079 => 'Dire Mathilde',
				74500 => 'Marauder Svaard',
				71161 => 'Vigilant Laranthir',
				72004 => 'Crusader Ossa',
				72893 => 'Wanderer Ruka',
				72256 => 'Trailblazer Pahua',
				'87858: Plaguedoctor Nerashi' => '87858: Plaguedoctor Nerashi',
				46908 => 'Apothecary Ebonmane',
				47022 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6defcc534e7',
			'label' => 'swords (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'sword',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46774 => 'zojjas / berserker',
				46831 => 'beigarths knight',
				46983 => 'hronks magi',
				47040 => 'theodosuss cleric',
				47059 => 'soross assassin',
				49879 => 'keepers zealot',
				66672 => 'ventaris nomad',
				67938 => 'veratas sinister',
				70838 => 'yassiths viper',
				73724 => 'tizlaks commander',
				76730 => 'maklains minstrel',
				84876 => 'thetwins grieving',
				84939 => 'zehtukas harrier',
				85008 => 'nadijehs marshal',
				86662 => 'tixxs giver',
				89645 => 'steelstars diviner',
				46812 => 'Valkyrie Stonecleaver',
				47002 => 'Soldier Chorben',
				46793 => 'Rampager Coalforge',
				46945 => 'Cavalier Angchu',
				46926 => 'Settler Leftpaw',
				46888 => 'Sentinel Tonn',
				46869 => 'Shaman	Zintl',
				46850 => 'Carrion	Occam',
				46964 => 'Rabid	Grizzlemouth',
				47078 => 'Dire	Mathilde',
				75897 => 'Marauder	Svaard',
				74064 => 'Vigilant	Laranthir',
				73373 => 'Crusader	Ossa',
				72079 => 'Wanderer	Ruka',
				73984 => 'Trailblazer	Pahua',
				87885 => 'Plaguedoctor	Nerashi',
				46907 => 'Apothecary	Ebonmane',
				47021 => 'Celestial	Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6def03534e6',
			'label' => 'daggers (offhand 2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'Dagger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46760 => 'zojjas berserker',
				46817 => 'beigarths knight',
				46969 => 'hronks magi',
				47026 => 'theodosuss cleric',
				47045 => 'soross assassin',
				49882 => 'keepers zealot',
				66687 => 'ventaris nomad',
				67948 => 'veratas sinister',
				73059 => 'tizlaks commander',
				74179 => 'yassiths viper',
				75388 => 'maklains minstrel',
				84909 => 'nadijehs marshal',
				84936 => 'thetwin grieving',
				85051 => 'zehtukas harrier',
				86689 => 'tixxs giver',
				89906 => 'steelstars diviner',
				46798 => 'Valkyrie Stonecleaver',
				46988 => 'Soldier Chorben',
				46779 => 'Rampager Coalforge',
				46931 => 'Cavalier Angchu',
				46912 => 'Settler Leftpaw',
				46874 => 'Sentinel Tonn',
				46855 => 'Shaman Zintl',
				46836 => 'Carrion Occam',
				46950 => 'Rabid Grizzlemouth',
				47064 => 'Dire Mathilde',
				73343 => 'Marauder Svaard',
				72546 => 'Vigilant Laranthir',
				'71917: Crusader Ossa' => '71917: Crusader Ossa',
				72359 => 'Wanderer Ruka',
				75422 => 'Trailblazer Pahua',
				87823 => 'Plaguedoctor Nerashi',
				46893 => 'Apothecary Ebonmane',
				47007 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c6ea9678e88a',
			'label' => 'warhorn (oh2)',
			'name' => 'oh2',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c6dea03534e5',
						'operator' => '==',
						'value' => 'warhorn',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				46777 => 'zojjasherald	warhorn	berserker',
				46834 => 'beigarthsherald	warhorn	knight',
				46986 => 'hronksherald	warhorn	magi',
				47043 => 'theodosussherald	warhorn	cleric',
				47062 => 'sorossherald	warhorn	assassin',
				49883 => 'keepersherald	warhorn	zealot',
				66678 => 'ventarisherald	warhorn	nomad',
				67936 => 'veratasherald	warhorn	sinister',
				71116 => 'maklainsherald	warhorn	minstrel',
				71117 => 'tizlaksherald	warhorn	commander',
				75325 => 'yassithsherald	warhorn	viper',
				84973 => 'zehtukasherald	warhorn	harrier',
				85074 => 'thetwinsherald	warhorn	grieving',
				85116 => 'nadijehs marshal',
				86440 => 'tixxsherald giver',
				89624 => 'steelstars diviner',
				46815 => 'Valkyrie Stonecleaver',
				47005 => 'Soldier Chorben',
				46796 => 'Rampager Coalforge',
				46948 => 'Cavalier Angchu',
				46929 => 'Settler Leftpaw',
				46891 => 'Sentinel Tonn',
				46872 => 'Shaman Zintl',
				46853 => 'Carrion Occam',
				46967 => 'Rabid Grizzlemouth',
				47081 => 'Dire Mathilde',
				75201 => 'Marauder Svaard',
				76824 => 'Vigilant Laranthir',
				71005 => 'Crusader Ossa',
				75042 => 'Wanderer Ruka',
				75697 => 'Trailblazer Pahua',
				87898 => 'Plaguedoctor Nerashi',
				46910 => 'Apothecary Ebonmane',
				47024 => 'Celestial Wupwup',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:elementalist',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:engineer',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:guardian',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:mesmer',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:necromancer',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:ranger',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:revenant',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:thief',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:warrior',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
